# valley:setup/place_ruin  -- GENERATED by tools/scripts/plan_town.py, do not hand-edit.
# Invoked positioned at the HEARTHSTONE (valley_core.js placeRuin).
# The ruin is nova_structures:wild_ruin/wild_ruin_23; its hearthstone is local [7, 1, 6].

fill ~-11 ~1 ~-11 ~11 ~16 ~11 minecraft:air
fill ~-11 ~-6 ~-11 ~11 ~-2 ~11 minecraft:stone
fill ~-11 ~-1 ~-11 ~11 ~-1 ~11 minecraft:dirt
fill ~-11 ~0 ~-11 ~11 ~0 ~11 minecraft:grass_block
place template nova_structures:wild_ruin/wild_ruin_23 ~-7 ~-1 ~-6
fill ~-7 ~-1 ~-6 ~2 ~9 ~2 minecraft:air replace minecraft:jigsaw
fill ~-11 ~0 ~-11 ~11 ~0 ~11 minecraft:grass_block replace minecraft:air
# the flat grey hearthstone Q2 sends her to, and two blocks of air over it
setblock ~0 ~0 ~0 minecraft:polished_andesite
setblock ~0 ~1 ~0 minecraft:air
setblock ~0 ~2 ~0 minecraft:air
setblock ~-1 ~1 ~0 minecraft:campfire[lit=false]
# four years of nobody keeping the yard
setblock ~-7 ~1 ~6 minecraft:oak_fence
setblock ~-6 ~1 ~7 minecraft:oak_fence
setblock ~7 ~1 ~-6 minecraft:mossy_cobblestone
setblock ~-8 ~1 ~-7 minecraft:mossy_cobblestone
setblock ~6 ~1 ~7 minecraft:oak_fence
# the gate, so the end of the lit path is unmistakably the place
setblock ~0 ~1 ~8 minecraft:oak_fence
setblock ~0 ~2 ~8 minecraft:oak_sign[rotation=8]{front_text:{messages:['{"text":"KETTLE FARM"}','{"text":""}','{"text":"J. Kettle"}','{"text":"mind the weeds"}'],color:"gray"}}
setblock ~-1 ~1 ~8 minecraft:lantern[hanging=false]
setblock ~1 ~1 ~8 minecraft:lantern[hanging=false]
title @a times 10 70 20
title @a subtitle {"text":"Three walls, a chimney, a cold hearth.","color":"gray","italic":true}
title @a title {"text":"The Old Kettle Farm","color":"gold"}
execute at @a run playsound minecraft:block.bell.resonate master @a ~ ~ ~ 1 0.9
