# valley:act1/cottage  -- GENERATED by tools/scripts/plan_town.py, do not hand-edit.
# Invoked positioned at the HOME waystone (valley_checks.js, Q2).
# Home is the waystone; the hearthstone is home + [0,-1,0]; the ruin comes down
# and kaisyn:village/meadow_swiss/houses/meadow_small_house_1 goes up around it, so the hearthstone ends up on the cottage floor.

# 1. clear the ruin, and level the yard Q9 and Q10 are marked out on
fill ~-11 ~0 ~-14 ~11 ~15 ~11 minecraft:air
fill ~-11 ~-4 ~-14 ~11 ~-3 ~11 minecraft:dirt
fill ~-11 ~-2 ~-14 ~11 ~-2 ~11 minecraft:coarse_dirt
fill ~-11 ~-1 ~-14 ~11 ~-1 ~11 minecraft:grass_block

# 2. the cottage, placed so its interior floor centre IS the hearthstone
place template kaisyn:village/meadow_swiss/houses/meadow_small_house_1 ~-4 ~-1 ~-4
fill ~-4 ~-1 ~-4 ~4 ~8 ~4 minecraft:air replace minecraft:jigsaw
fill ~-4 ~-1 ~-4 ~-3 ~8 ~4 minecraft:stone_bricks replace minecraft:cyan_concrete
fill ~0 ~-1 ~-4 ~1 ~8 ~4 minecraft:stone_bricks replace minecraft:cyan_concrete
fill ~4 ~-1 ~-4 ~4 ~8 ~4 minecraft:stone_bricks replace minecraft:cyan_concrete
fill ~-4 ~-1 ~-4 ~4 ~8 ~4 minecraft:gravel replace minecraft:cyan_concrete
fill ~-11 ~-1 ~-14 ~11 ~-1 ~11 minecraft:grass_block replace minecraft:air

# 3. Q3 hangs the door, the two windows, the bed and the sconce herself, so the
#    template's own door, glass and bed come out and leave the holes behind.
fill ~-4 ~-1 ~-4 ~4 ~8 ~4 minecraft:air replace minecraft:dark_oak_door
fill ~-4 ~-1 ~-4 ~4 ~8 ~4 minecraft:air replace minecraft:white_stained_glass_pane
fill ~-4 ~-1 ~-4 ~4 ~8 ~4 minecraft:air replace minecraft:green_bed

# 4. the hearthstone stays a hearthstone, and Home stands on it
setblock ~0 ~-1 ~0 minecraft:polished_andesite
setblock ~0 ~0 ~0 waystones:waystone{WaystoneName:"Home"}
# the wool mat Q3 puts the Red Bed on, and the hook for the sconce
setblock ~-1 ~-1 ~-1 minecraft:white_wool
setblock ~-1 ~-1 ~0 minecraft:white_wool
setblock ~-2 ~-1 ~-1 minecraft:red_carpet
setblock ~1 ~0 ~1 minecraft:oak_fence

# 5. HOME_PORCH: the bare fortieth post lands at home + [3,0,0] (Q90), so that
#    cell is kept clear with solid ground under it.
setblock ~3 ~-1 ~0 minecraft:cobblestone
setblock ~3 ~0 ~0 minecraft:air
setblock ~3 ~1 ~0 minecraft:air
fill ~1 ~-1 ~1 ~4 ~-1 ~3 minecraft:cobblestone

# 6. Q9: the 3x9 patch behind the house. 27 dirt_path tiles, one per seed.
fill ~-8 ~-1 ~-8 ~0 ~-1 ~-6 minecraft:dirt_path
setblock ~-4 ~-1 ~-10 minecraft:water
# Q10: the pen. 23 cobblestone footings and one polished andesite gate slot.
fill ~1 ~-1 ~-12 ~7 ~-1 ~-12 minecraft:cobblestone
fill ~1 ~-1 ~-6 ~7 ~-1 ~-6 minecraft:cobblestone
fill ~1 ~-1 ~-11 ~1 ~-1 ~-7 minecraft:cobblestone
fill ~7 ~-1 ~-11 ~7 ~-1 ~-7 minecraft:cobblestone
setblock ~4 ~-1 ~-6 minecraft:polished_andesite
setblock ~-4 ~0 ~-5 minecraft:oak_sign[rotation=8]{front_text:{messages:['{"text":"3 x 9"}','{"text":"wheat"}','{"text":"carrots"}','{"text":"potatoes"}'],color:"gray"}}
setblock ~4 ~0 ~-5 minecraft:oak_sign[rotation=8]{front_text:{messages:['{"text":"THE PEN"}','{"text":"fence the stone"}','{"text":"gate on the grey"}','{"text":""}'],color:"gray"}}

tellraw @a[distance=..64] [{"text":"Josie: ","color":"gray"},{"text":"\"Four walls and a door. That is a house. What you do next makes it a home.\"","color":"white","italic":true}]
playsound minecraft:block.wood.place master @a[distance=..64] ~ ~ ~ 1 0.9
