# valley:act1/square_path  -- GENERATED by tools/scripts/plan_town.py.
# Q7 reward, invoked positioned at the Town Anchor.
fill ~-3 ~1 ~-3 ~3 ~6 ~3 minecraft:air
fill ~-3 ~-5 ~-3 ~3 ~-1 ~3 minecraft:dirt
fill ~-3 ~0 ~-3 ~3 ~0 ~3 minecraft:stone_bricks
setblock ~0 ~0 ~0 minecraft:polished_andesite
fill ~-1 ~1 ~1 ~1 ~6 ~24 minecraft:air
fill ~-1 ~-5 ~1 ~1 ~-1 ~24 minecraft:dirt
fill ~-1 ~0 ~1 ~1 ~0 ~24 minecraft:cobblestone
fill ~0 ~0 ~1 ~0 ~0 ~24 minecraft:polished_andesite
fill ~-2 ~0 ~4 ~-2 ~0 ~20 minecraft:gravel
fill ~2 ~0 ~4 ~2 ~0 ~20 minecraft:gravel
# the first two lamp posts: 2 of 40 (valley_core.js LAMPS_Q07).
setblock ~-2 ~1 ~8 minecraft:oak_fence
setblock ~-2 ~2 ~8 createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]
setblock ~2 ~1 ~16 minecraft:oak_fence
setblock ~2 ~2 ~16 createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]
setblock ~-2 ~1 ~2 minecraft:oak_fence
setblock ~2 ~1 ~2 minecraft:oak_fence
setblock ~-2 ~2 ~2 minecraft:lantern[hanging=false]
setblock ~2 ~2 ~2 minecraft:lantern[hanging=false]
tellraw @a[distance=..64] [{"text":"Josie: ","color":"gray"},{"text":"\"Bram surveyed that flat twice and never drove the stake. You drove it. That is the whole difference.\"","color":"white","italic":true}]
playsound minecraft:block.stone.place master @a[distance=..64] ~ ~ ~ 1 0.8
