# valley:act1/square_path  -- GENERATED by tools/scripts/plan_town.py.
# Q7 reward, invoked positioned at the Town Anchor.
# The stake pad is on the plaza, which is the datum; the twenty-four blocks of High
# Street south of it are laid COLUMN BY COLUMN at the level act1_streets gave them,
# because the street is a staircase down the hill now and a flat re-lay would cut a
# trench through it at Q7.
fill ~-3 ~1 ~-3 ~3 ~6 ~3 minecraft:air
fill ~-3 ~-5 ~-3 ~3 ~-1 ~3 minecraft:dirt
fill ~-3 ~0 ~-3 ~3 ~0 ~3 minecraft:stone_bricks
setblock ~0 ~0 ~0 minecraft:polished_andesite
fill ~-1 ~1 ~1 ~-1 ~6 ~1 minecraft:air
fill ~-1 ~-5 ~1 ~-1 ~-1 ~1 minecraft:dirt
setblock ~-1 ~0 ~1 minecraft:cobblestone
fill ~0 ~1 ~1 ~0 ~6 ~1 minecraft:air
fill ~0 ~-5 ~1 ~0 ~-1 ~1 minecraft:dirt
setblock ~0 ~0 ~1 minecraft:polished_andesite
fill ~1 ~1 ~1 ~1 ~6 ~1 minecraft:air
fill ~1 ~-5 ~1 ~1 ~-1 ~1 minecraft:dirt
setblock ~1 ~0 ~1 minecraft:cobblestone
fill ~-1 ~1 ~2 ~-1 ~6 ~2 minecraft:air
fill ~-1 ~-5 ~2 ~-1 ~-1 ~2 minecraft:dirt
setblock ~-1 ~0 ~2 minecraft:cobblestone
fill ~0 ~1 ~2 ~0 ~6 ~2 minecraft:air
fill ~0 ~-5 ~2 ~0 ~-1 ~2 minecraft:dirt
setblock ~0 ~0 ~2 minecraft:polished_andesite
fill ~1 ~1 ~2 ~1 ~6 ~2 minecraft:air
fill ~1 ~-5 ~2 ~1 ~-1 ~2 minecraft:dirt
setblock ~1 ~0 ~2 minecraft:cobblestone
fill ~-1 ~1 ~3 ~-1 ~6 ~3 minecraft:air
fill ~-1 ~-5 ~3 ~-1 ~-1 ~3 minecraft:dirt
setblock ~-1 ~0 ~3 minecraft:cobblestone
fill ~0 ~1 ~3 ~0 ~6 ~3 minecraft:air
fill ~0 ~-5 ~3 ~0 ~-1 ~3 minecraft:dirt
setblock ~0 ~0 ~3 minecraft:polished_andesite
fill ~1 ~1 ~3 ~1 ~6 ~3 minecraft:air
fill ~1 ~-5 ~3 ~1 ~-1 ~3 minecraft:dirt
setblock ~1 ~0 ~3 minecraft:cobblestone
fill ~-2 ~1 ~4 ~-2 ~6 ~4 minecraft:air
fill ~-2 ~-5 ~4 ~-2 ~-1 ~4 minecraft:dirt
setblock ~-2 ~0 ~4 minecraft:gravel
fill ~-1 ~1 ~4 ~-1 ~6 ~4 minecraft:air
fill ~-1 ~-5 ~4 ~-1 ~-1 ~4 minecraft:dirt
setblock ~-1 ~0 ~4 minecraft:cobblestone
fill ~0 ~1 ~4 ~0 ~6 ~4 minecraft:air
fill ~0 ~-5 ~4 ~0 ~-1 ~4 minecraft:dirt
setblock ~0 ~0 ~4 minecraft:polished_andesite
fill ~1 ~1 ~4 ~1 ~6 ~4 minecraft:air
fill ~1 ~-5 ~4 ~1 ~-1 ~4 minecraft:dirt
setblock ~1 ~0 ~4 minecraft:cobblestone
fill ~2 ~1 ~4 ~2 ~6 ~4 minecraft:air
fill ~2 ~-5 ~4 ~2 ~-1 ~4 minecraft:dirt
setblock ~2 ~0 ~4 minecraft:gravel
fill ~-2 ~1 ~5 ~-2 ~6 ~5 minecraft:air
fill ~-2 ~-5 ~5 ~-2 ~-1 ~5 minecraft:dirt
setblock ~-2 ~0 ~5 minecraft:gravel
fill ~-1 ~1 ~5 ~-1 ~6 ~5 minecraft:air
fill ~-1 ~-5 ~5 ~-1 ~-1 ~5 minecraft:dirt
setblock ~-1 ~0 ~5 minecraft:cobblestone
fill ~0 ~1 ~5 ~0 ~6 ~5 minecraft:air
fill ~0 ~-5 ~5 ~0 ~-1 ~5 minecraft:dirt
setblock ~0 ~0 ~5 minecraft:polished_andesite
fill ~1 ~1 ~5 ~1 ~6 ~5 minecraft:air
fill ~1 ~-5 ~5 ~1 ~-1 ~5 minecraft:dirt
setblock ~1 ~0 ~5 minecraft:cobblestone
fill ~2 ~1 ~5 ~2 ~6 ~5 minecraft:air
fill ~2 ~-5 ~5 ~2 ~-1 ~5 minecraft:dirt
setblock ~2 ~0 ~5 minecraft:gravel
fill ~-2 ~1 ~6 ~-2 ~6 ~6 minecraft:air
fill ~-2 ~-5 ~6 ~-2 ~-1 ~6 minecraft:dirt
setblock ~-2 ~0 ~6 minecraft:gravel
fill ~-1 ~1 ~6 ~-1 ~6 ~6 minecraft:air
fill ~-1 ~-5 ~6 ~-1 ~-1 ~6 minecraft:dirt
setblock ~-1 ~0 ~6 minecraft:cobblestone
fill ~0 ~1 ~6 ~0 ~6 ~6 minecraft:air
fill ~0 ~-5 ~6 ~0 ~-1 ~6 minecraft:dirt
setblock ~0 ~0 ~6 minecraft:polished_andesite
fill ~1 ~1 ~6 ~1 ~6 ~6 minecraft:air
fill ~1 ~-5 ~6 ~1 ~-1 ~6 minecraft:dirt
setblock ~1 ~0 ~6 minecraft:cobblestone
fill ~2 ~1 ~6 ~2 ~6 ~6 minecraft:air
fill ~2 ~-5 ~6 ~2 ~-1 ~6 minecraft:dirt
setblock ~2 ~0 ~6 minecraft:gravel
fill ~-2 ~1 ~7 ~-2 ~6 ~7 minecraft:air
fill ~-2 ~-5 ~7 ~-2 ~-1 ~7 minecraft:dirt
setblock ~-2 ~0 ~7 minecraft:gravel
fill ~-1 ~1 ~7 ~-1 ~6 ~7 minecraft:air
fill ~-1 ~-5 ~7 ~-1 ~-1 ~7 minecraft:dirt
setblock ~-1 ~0 ~7 minecraft:cobblestone
fill ~0 ~1 ~7 ~0 ~6 ~7 minecraft:air
fill ~0 ~-5 ~7 ~0 ~-1 ~7 minecraft:dirt
setblock ~0 ~0 ~7 minecraft:polished_andesite
fill ~1 ~1 ~7 ~1 ~6 ~7 minecraft:air
fill ~1 ~-5 ~7 ~1 ~-1 ~7 minecraft:dirt
setblock ~1 ~0 ~7 minecraft:cobblestone
fill ~2 ~1 ~7 ~2 ~6 ~7 minecraft:air
fill ~2 ~-5 ~7 ~2 ~-1 ~7 minecraft:dirt
setblock ~2 ~0 ~7 minecraft:gravel
fill ~-2 ~1 ~8 ~-2 ~6 ~8 minecraft:air
fill ~-2 ~-5 ~8 ~-2 ~-1 ~8 minecraft:dirt
setblock ~-2 ~0 ~8 minecraft:gravel
fill ~-1 ~1 ~8 ~-1 ~6 ~8 minecraft:air
fill ~-1 ~-5 ~8 ~-1 ~-1 ~8 minecraft:dirt
setblock ~-1 ~0 ~8 minecraft:cobblestone
fill ~0 ~1 ~8 ~0 ~6 ~8 minecraft:air
fill ~0 ~-5 ~8 ~0 ~-1 ~8 minecraft:dirt
setblock ~0 ~0 ~8 minecraft:polished_andesite
fill ~1 ~1 ~8 ~1 ~6 ~8 minecraft:air
fill ~1 ~-5 ~8 ~1 ~-1 ~8 minecraft:dirt
setblock ~1 ~0 ~8 minecraft:cobblestone
fill ~2 ~1 ~8 ~2 ~6 ~8 minecraft:air
fill ~2 ~-5 ~8 ~2 ~-1 ~8 minecraft:dirt
setblock ~2 ~0 ~8 minecraft:gravel
fill ~-2 ~1 ~9 ~-2 ~6 ~9 minecraft:air
fill ~-2 ~-5 ~9 ~-2 ~-1 ~9 minecraft:dirt
setblock ~-2 ~0 ~9 minecraft:gravel
fill ~-1 ~1 ~9 ~-1 ~6 ~9 minecraft:air
fill ~-1 ~-5 ~9 ~-1 ~-1 ~9 minecraft:dirt
setblock ~-1 ~0 ~9 minecraft:cobblestone
fill ~0 ~1 ~9 ~0 ~6 ~9 minecraft:air
fill ~0 ~-5 ~9 ~0 ~-1 ~9 minecraft:dirt
setblock ~0 ~0 ~9 minecraft:polished_andesite
fill ~1 ~1 ~9 ~1 ~6 ~9 minecraft:air
fill ~1 ~-5 ~9 ~1 ~-1 ~9 minecraft:dirt
setblock ~1 ~0 ~9 minecraft:cobblestone
fill ~2 ~1 ~9 ~2 ~6 ~9 minecraft:air
fill ~2 ~-5 ~9 ~2 ~-1 ~9 minecraft:dirt
setblock ~2 ~0 ~9 minecraft:gravel
fill ~-2 ~1 ~10 ~-2 ~6 ~10 minecraft:air
fill ~-2 ~-5 ~10 ~-2 ~-1 ~10 minecraft:dirt
setblock ~-2 ~0 ~10 minecraft:gravel
fill ~-1 ~1 ~10 ~-1 ~6 ~10 minecraft:air
fill ~-1 ~-5 ~10 ~-1 ~-1 ~10 minecraft:dirt
setblock ~-1 ~0 ~10 minecraft:cobblestone
fill ~0 ~1 ~10 ~0 ~6 ~10 minecraft:air
fill ~0 ~-5 ~10 ~0 ~-1 ~10 minecraft:dirt
setblock ~0 ~0 ~10 minecraft:polished_andesite
fill ~1 ~1 ~10 ~1 ~6 ~10 minecraft:air
fill ~1 ~-5 ~10 ~1 ~-1 ~10 minecraft:dirt
setblock ~1 ~0 ~10 minecraft:cobblestone
fill ~2 ~1 ~10 ~2 ~6 ~10 minecraft:air
fill ~2 ~-5 ~10 ~2 ~-1 ~10 minecraft:dirt
setblock ~2 ~0 ~10 minecraft:gravel
fill ~-2 ~1 ~11 ~-2 ~6 ~11 minecraft:air
fill ~-2 ~-5 ~11 ~-2 ~-1 ~11 minecraft:dirt
setblock ~-2 ~0 ~11 minecraft:gravel
fill ~-1 ~1 ~11 ~-1 ~6 ~11 minecraft:air
fill ~-1 ~-5 ~11 ~-1 ~-1 ~11 minecraft:dirt
setblock ~-1 ~0 ~11 minecraft:cobblestone
fill ~0 ~1 ~11 ~0 ~6 ~11 minecraft:air
fill ~0 ~-5 ~11 ~0 ~-1 ~11 minecraft:dirt
setblock ~0 ~0 ~11 minecraft:polished_andesite
fill ~1 ~1 ~11 ~1 ~6 ~11 minecraft:air
fill ~1 ~-5 ~11 ~1 ~-1 ~11 minecraft:dirt
setblock ~1 ~0 ~11 minecraft:cobblestone
fill ~2 ~1 ~11 ~2 ~6 ~11 minecraft:air
fill ~2 ~-5 ~11 ~2 ~-1 ~11 minecraft:dirt
setblock ~2 ~0 ~11 minecraft:gravel
fill ~-2 ~1 ~12 ~-2 ~6 ~12 minecraft:air
fill ~-2 ~-5 ~12 ~-2 ~-1 ~12 minecraft:dirt
setblock ~-2 ~0 ~12 minecraft:gravel
fill ~-1 ~1 ~12 ~-1 ~6 ~12 minecraft:air
fill ~-1 ~-5 ~12 ~-1 ~-1 ~12 minecraft:dirt
setblock ~-1 ~0 ~12 minecraft:cobblestone
fill ~0 ~1 ~12 ~0 ~6 ~12 minecraft:air
fill ~0 ~-5 ~12 ~0 ~-1 ~12 minecraft:dirt
setblock ~0 ~0 ~12 minecraft:polished_andesite
fill ~1 ~1 ~12 ~1 ~6 ~12 minecraft:air
fill ~1 ~-5 ~12 ~1 ~-1 ~12 minecraft:dirt
setblock ~1 ~0 ~12 minecraft:cobblestone
fill ~2 ~1 ~12 ~2 ~6 ~12 minecraft:air
fill ~2 ~-5 ~12 ~2 ~-1 ~12 minecraft:dirt
setblock ~2 ~0 ~12 minecraft:gravel
fill ~-2 ~1 ~13 ~-2 ~6 ~13 minecraft:air
fill ~-2 ~-5 ~13 ~-2 ~-1 ~13 minecraft:dirt
setblock ~-2 ~0 ~13 minecraft:gravel
fill ~-1 ~1 ~13 ~-1 ~6 ~13 minecraft:air
fill ~-1 ~-5 ~13 ~-1 ~-1 ~13 minecraft:dirt
setblock ~-1 ~0 ~13 minecraft:cobblestone
fill ~0 ~1 ~13 ~0 ~6 ~13 minecraft:air
fill ~0 ~-5 ~13 ~0 ~-1 ~13 minecraft:dirt
setblock ~0 ~0 ~13 minecraft:polished_andesite
fill ~1 ~1 ~13 ~1 ~6 ~13 minecraft:air
fill ~1 ~-5 ~13 ~1 ~-1 ~13 minecraft:dirt
setblock ~1 ~0 ~13 minecraft:cobblestone
fill ~2 ~1 ~13 ~2 ~6 ~13 minecraft:air
fill ~2 ~-5 ~13 ~2 ~-1 ~13 minecraft:dirt
setblock ~2 ~0 ~13 minecraft:gravel
fill ~-2 ~1 ~14 ~-2 ~6 ~14 minecraft:air
fill ~-2 ~-5 ~14 ~-2 ~-1 ~14 minecraft:dirt
setblock ~-2 ~0 ~14 minecraft:gravel
fill ~-1 ~1 ~14 ~-1 ~6 ~14 minecraft:air
fill ~-1 ~-5 ~14 ~-1 ~-1 ~14 minecraft:dirt
setblock ~-1 ~0 ~14 minecraft:cobblestone
fill ~0 ~1 ~14 ~0 ~6 ~14 minecraft:air
fill ~0 ~-5 ~14 ~0 ~-1 ~14 minecraft:dirt
setblock ~0 ~0 ~14 minecraft:polished_andesite
fill ~1 ~1 ~14 ~1 ~6 ~14 minecraft:air
fill ~1 ~-5 ~14 ~1 ~-1 ~14 minecraft:dirt
setblock ~1 ~0 ~14 minecraft:cobblestone
fill ~2 ~1 ~14 ~2 ~6 ~14 minecraft:air
fill ~2 ~-5 ~14 ~2 ~-1 ~14 minecraft:dirt
setblock ~2 ~0 ~14 minecraft:gravel
fill ~-2 ~1 ~15 ~-2 ~6 ~15 minecraft:air
fill ~-2 ~-5 ~15 ~-2 ~-1 ~15 minecraft:dirt
setblock ~-2 ~0 ~15 minecraft:gravel
fill ~-1 ~1 ~15 ~-1 ~6 ~15 minecraft:air
fill ~-1 ~-5 ~15 ~-1 ~-1 ~15 minecraft:dirt
setblock ~-1 ~0 ~15 minecraft:cobblestone
fill ~0 ~1 ~15 ~0 ~6 ~15 minecraft:air
fill ~0 ~-5 ~15 ~0 ~-1 ~15 minecraft:dirt
setblock ~0 ~0 ~15 minecraft:polished_andesite
fill ~1 ~1 ~15 ~1 ~6 ~15 minecraft:air
fill ~1 ~-5 ~15 ~1 ~-1 ~15 minecraft:dirt
setblock ~1 ~0 ~15 minecraft:cobblestone
fill ~2 ~1 ~15 ~2 ~6 ~15 minecraft:air
fill ~2 ~-5 ~15 ~2 ~-1 ~15 minecraft:dirt
setblock ~2 ~0 ~15 minecraft:gravel
fill ~-2 ~2 ~16 ~-2 ~7 ~16 minecraft:air
fill ~-2 ~-4 ~16 ~-2 ~0 ~16 minecraft:dirt
setblock ~-2 ~1 ~16 minecraft:gravel
fill ~-1 ~2 ~16 ~-1 ~7 ~16 minecraft:air
fill ~-1 ~-4 ~16 ~-1 ~0 ~16 minecraft:dirt
setblock ~-1 ~1 ~16 minecraft:cobblestone
fill ~0 ~2 ~16 ~0 ~7 ~16 minecraft:air
fill ~0 ~-4 ~16 ~0 ~0 ~16 minecraft:dirt
setblock ~0 ~1 ~16 minecraft:polished_andesite
fill ~1 ~2 ~16 ~1 ~7 ~16 minecraft:air
fill ~1 ~-4 ~16 ~1 ~0 ~16 minecraft:dirt
setblock ~1 ~1 ~16 minecraft:cobblestone
fill ~2 ~2 ~16 ~2 ~7 ~16 minecraft:air
fill ~2 ~-4 ~16 ~2 ~0 ~16 minecraft:dirt
setblock ~2 ~1 ~16 minecraft:gravel
fill ~-2 ~2 ~17 ~-2 ~7 ~17 minecraft:air
fill ~-2 ~-4 ~17 ~-2 ~0 ~17 minecraft:dirt
setblock ~-2 ~1 ~17 minecraft:gravel
fill ~-1 ~2 ~17 ~-1 ~7 ~17 minecraft:air
fill ~-1 ~-4 ~17 ~-1 ~0 ~17 minecraft:dirt
setblock ~-1 ~1 ~17 minecraft:cobblestone
fill ~0 ~2 ~17 ~0 ~7 ~17 minecraft:air
fill ~0 ~-4 ~17 ~0 ~0 ~17 minecraft:dirt
setblock ~0 ~1 ~17 minecraft:polished_andesite
fill ~1 ~2 ~17 ~1 ~7 ~17 minecraft:air
fill ~1 ~-4 ~17 ~1 ~0 ~17 minecraft:dirt
setblock ~1 ~1 ~17 minecraft:cobblestone
fill ~2 ~2 ~17 ~2 ~7 ~17 minecraft:air
fill ~2 ~-4 ~17 ~2 ~0 ~17 minecraft:dirt
setblock ~2 ~1 ~17 minecraft:gravel
fill ~-2 ~2 ~18 ~-2 ~7 ~18 minecraft:air
fill ~-2 ~-4 ~18 ~-2 ~0 ~18 minecraft:dirt
setblock ~-2 ~1 ~18 minecraft:gravel
fill ~-1 ~2 ~18 ~-1 ~7 ~18 minecraft:air
fill ~-1 ~-4 ~18 ~-1 ~0 ~18 minecraft:dirt
setblock ~-1 ~1 ~18 minecraft:cobblestone
fill ~0 ~2 ~18 ~0 ~7 ~18 minecraft:air
fill ~0 ~-4 ~18 ~0 ~0 ~18 minecraft:dirt
setblock ~0 ~1 ~18 minecraft:polished_andesite
fill ~1 ~2 ~18 ~1 ~7 ~18 minecraft:air
fill ~1 ~-4 ~18 ~1 ~0 ~18 minecraft:dirt
setblock ~1 ~1 ~18 minecraft:cobblestone
fill ~2 ~2 ~18 ~2 ~7 ~18 minecraft:air
fill ~2 ~-4 ~18 ~2 ~0 ~18 minecraft:dirt
setblock ~2 ~1 ~18 minecraft:gravel
fill ~-2 ~2 ~19 ~-2 ~7 ~19 minecraft:air
fill ~-2 ~-4 ~19 ~-2 ~0 ~19 minecraft:dirt
setblock ~-2 ~1 ~19 minecraft:gravel
fill ~-1 ~2 ~19 ~-1 ~7 ~19 minecraft:air
fill ~-1 ~-4 ~19 ~-1 ~0 ~19 minecraft:dirt
setblock ~-1 ~1 ~19 minecraft:cobblestone
fill ~0 ~2 ~19 ~0 ~7 ~19 minecraft:air
fill ~0 ~-4 ~19 ~0 ~0 ~19 minecraft:dirt
setblock ~0 ~1 ~19 minecraft:polished_andesite
fill ~1 ~2 ~19 ~1 ~7 ~19 minecraft:air
fill ~1 ~-4 ~19 ~1 ~0 ~19 minecraft:dirt
setblock ~1 ~1 ~19 minecraft:cobblestone
fill ~2 ~2 ~19 ~2 ~7 ~19 minecraft:air
fill ~2 ~-4 ~19 ~2 ~0 ~19 minecraft:dirt
setblock ~2 ~1 ~19 minecraft:gravel
fill ~-2 ~1 ~20 ~-2 ~6 ~20 minecraft:air
fill ~-2 ~-5 ~20 ~-2 ~-1 ~20 minecraft:dirt
setblock ~-2 ~0 ~20 minecraft:gravel
fill ~-1 ~1 ~20 ~-1 ~6 ~20 minecraft:air
fill ~-1 ~-5 ~20 ~-1 ~-1 ~20 minecraft:dirt
setblock ~-1 ~0 ~20 minecraft:cobblestone
fill ~0 ~1 ~20 ~0 ~6 ~20 minecraft:air
fill ~0 ~-5 ~20 ~0 ~-1 ~20 minecraft:dirt
setblock ~0 ~0 ~20 minecraft:polished_andesite
fill ~1 ~1 ~20 ~1 ~6 ~20 minecraft:air
fill ~1 ~-5 ~20 ~1 ~-1 ~20 minecraft:dirt
setblock ~1 ~0 ~20 minecraft:cobblestone
fill ~2 ~1 ~20 ~2 ~6 ~20 minecraft:air
fill ~2 ~-5 ~20 ~2 ~-1 ~20 minecraft:dirt
setblock ~2 ~0 ~20 minecraft:gravel
fill ~-1 ~1 ~21 ~-1 ~6 ~21 minecraft:air
fill ~-1 ~-5 ~21 ~-1 ~-1 ~21 minecraft:dirt
setblock ~-1 ~0 ~21 minecraft:cobblestone
fill ~0 ~1 ~21 ~0 ~6 ~21 minecraft:air
fill ~0 ~-5 ~21 ~0 ~-1 ~21 minecraft:dirt
setblock ~0 ~0 ~21 minecraft:polished_andesite
fill ~1 ~1 ~21 ~1 ~6 ~21 minecraft:air
fill ~1 ~-5 ~21 ~1 ~-1 ~21 minecraft:dirt
setblock ~1 ~0 ~21 minecraft:cobblestone
fill ~-1 ~1 ~22 ~-1 ~6 ~22 minecraft:air
fill ~-1 ~-5 ~22 ~-1 ~-1 ~22 minecraft:dirt
setblock ~-1 ~0 ~22 minecraft:cobblestone
fill ~0 ~1 ~22 ~0 ~6 ~22 minecraft:air
fill ~0 ~-5 ~22 ~0 ~-1 ~22 minecraft:dirt
setblock ~0 ~0 ~22 minecraft:polished_andesite
fill ~1 ~1 ~22 ~1 ~6 ~22 minecraft:air
fill ~1 ~-5 ~22 ~1 ~-1 ~22 minecraft:dirt
setblock ~1 ~0 ~22 minecraft:cobblestone
fill ~-1 ~1 ~23 ~-1 ~6 ~23 minecraft:air
fill ~-1 ~-5 ~23 ~-1 ~-1 ~23 minecraft:dirt
setblock ~-1 ~0 ~23 minecraft:cobblestone
fill ~0 ~1 ~23 ~0 ~6 ~23 minecraft:air
fill ~0 ~-5 ~23 ~0 ~-1 ~23 minecraft:dirt
setblock ~0 ~0 ~23 minecraft:polished_andesite
fill ~1 ~1 ~23 ~1 ~6 ~23 minecraft:air
fill ~1 ~-5 ~23 ~1 ~-1 ~23 minecraft:dirt
setblock ~1 ~0 ~23 minecraft:cobblestone
fill ~-1 ~1 ~24 ~-1 ~6 ~24 minecraft:air
fill ~-1 ~-5 ~24 ~-1 ~-1 ~24 minecraft:dirt
setblock ~-1 ~0 ~24 minecraft:cobblestone
fill ~0 ~1 ~24 ~0 ~6 ~24 minecraft:air
fill ~0 ~-5 ~24 ~0 ~-1 ~24 minecraft:dirt
setblock ~0 ~0 ~24 minecraft:polished_andesite
fill ~1 ~1 ~24 ~1 ~6 ~24 minecraft:air
fill ~1 ~-5 ~24 ~1 ~-1 ~24 minecraft:dirt
setblock ~1 ~0 ~24 minecraft:cobblestone
# the first two lamp posts: 2 of 40 (valley_core.js LAMPS_Q07).
setblock ~-2 ~1 ~8 minecraft:oak_fence
setblock ~-2 ~2 ~8 createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]
setblock ~2 ~2 ~16 minecraft:oak_fence
setblock ~2 ~3 ~16 createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]
setblock ~-2 ~1 ~2 minecraft:oak_fence
setblock ~2 ~1 ~2 minecraft:oak_fence
setblock ~-2 ~2 ~2 minecraft:lantern[hanging=false]
setblock ~2 ~2 ~2 minecraft:lantern[hanging=false]
tellraw @a[distance=..64] [{"text":"Josie: ","color":"gray"},{"text":"\"Stake's in. Bram will tell you he chose the spot. Let him.\"","color":"white","italic":true}]
playsound minecraft:block.stone.place master @a[distance=..64] ~ ~ ~ 1 0.8
