// GENERATED by compile_quests.py. Do not edit. Quest key -> FTB Quests id.
global.valleyQuestIds = {
 "t_one": "CBFF3FA693AF9A62",
 "t_two": "CC282A59ADD915BF",
 "t_three": "D75E0493A925501A"
}
global.valleyChapterIds = {
 "ztest": "7E1F7D28D9A33845"
}
