// priority: 2000
// valley_sites.js -- GENERATED by tools/scripts/plan_town.py. DO NOT HAND-EDIT.
//
// The fixed site registry, verbatim from pack/kubejs/data/valley/valley_sites.json,
// as a KubeJS global. The world is shipped, so every coordinate in the pack is a
// constant and this is where all three valley scripts read them from.
//
// priority 2000 loads it before town_plan.js (1000) and before every valley_*.js.

global.valleySites = {
 "_read_me": "Little Kettle Valley -- THE fixed site registry. GENERATED by tools/scripts/plan_town.py --site, from the chosen seed's master world. Every coordinate is ABSOLUTE and never changes: the world is shipped, so there is nothing left to derive at runtime. See docs/transitions-design.md step 4.",
 "seed": 5369984945557223422,
 "spawn": [
  -299,
  70,
  -58
 ],
 "hearth": [
  -319,
  74,
  32
 ],
 "home_waystone": [
  -319,
  75,
  32
 ],
 "anchor": [
  -302,
  69,
  -44
 ],
 "cottage": {
  "template": "kaisyn:village/meadow_swiss/houses/meadow_small_house_1",
  "place_origin": [
   -323,
   74,
   28
  ],
  "hearthstone": [
   -319,
   74,
   32
  ],
  "door": [
   -321,
   75,
   32
  ],
  "windows": [
   [
    -321,
    80,
    32
   ],
   [
    -319,
    76,
    30
   ],
   [
    -319,
    76,
    34
   ],
   [
    -319,
    80,
    30
   ],
   [
    -319,
    80,
    34
   ],
   [
    -317,
    76,
    32
   ],
   [
    -317,
    80,
    32
   ]
  ],
  "roof_patch": [
   [
    -322,
    82,
    32
   ],
   [
    -321,
    82,
    33
   ]
  ],
  "bed": [
   -320,
   74,
   31
  ],
  "gate_sign": [
   -319,
   76,
   42
  ],
  "porch": [
   -316,
   75,
   32
  ],
  "sconce": [
   -320,
   76,
   33
  ]
 },
 "plaza": [
  -314,
  -56,
  -290,
  -32
 ],
 "site_boxes": {
  "inn": [
   -288,
   -53,
   -266,
   -33
  ],
  "mill": [
   -350,
   -50,
   -330,
   -29
  ],
  "marnie_house": [
   -286,
   -71,
   -274,
   -59
  ],
  "pip_house": [
   -273,
   -71,
   -261,
   -59
  ],
  "granary": [
   -340,
   -28,
   -326,
   -15
  ],
  "garden": [
   -316,
   -86,
   -303,
   -74
  ],
  "store": [
   -298,
   -89,
   -284,
   -73
  ],
  "church": [
   -309,
   -70,
   -296,
   -60
  ],
  "town_hall": [
   -349,
   -80,
   -329,
   -64
  ],
  "newcomer_tess": [
   -284,
   -13,
   -269,
   3
  ],
  "newcomer_mab": [
   -334,
   -12,
   -319,
   3
  ],
  "newcomer_corin": [
   -254,
   -70,
   -239,
   -55
  ],
  "greenhouse": [
   -334,
   -61,
   -322,
   -53
  ],
  "bathhouse": [
   -275,
   -30,
   -267,
   -22
  ],
  "tobin_camp": [
   -274,
   -82,
   -266,
   -74
  ],
  "plaza": [
   -314,
   -56,
   -290,
   -32
  ],
  "cottage_plot": [
   -330,
   18,
   -308,
   43
  ]
 },
 "buildings": {
  "inn": {
   "template": "nova_structures:tavern/tavern_house_spruce",
   "rotation": "clockwise_90",
   "act": "act1",
   "label": "The Hearth",
   "level": 67,
   "origin": [
    -268,
    67,
    -51
   ],
   "footprint": {
    "x": [
     -286,
     -268
    ],
    "z": [
     -51,
     -35
    ]
   },
   "pad": [
    -288,
    -53,
    -266,
    -33
   ],
   "door": [
    -279,
    68,
    -48
   ],
   "door_facing": "south"
  },
  "mill": {
   "template": "kaisyn:village/sunflower_plains_farm/side/sunflower_plains_windmill_1",
   "rotation": "clockwise_90",
   "act": "act1",
   "label": "The Broken Mill",
   "level": 67,
   "origin": [
    -332,
    67,
    -48
   ],
   "footprint": {
    "x": [
     -348,
     -332
    ],
    "z": [
     -48,
     -31
    ]
   },
   "pad": [
    -350,
    -50,
    -330,
    -29
   ],
   "door": [
    -342,
    68,
    -39
   ],
   "door_facing": "east"
  },
  "marnie_house": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_small_house_2",
   "rotation": "none",
   "act": "act1",
   "label": "Marnie's Cottage",
   "level": 65,
   "origin": [
    -284,
    65,
    -69
   ],
   "footprint": {
    "x": [
     -284,
     -276
    ],
    "z": [
     -69,
     -61
    ]
   },
   "pad": [
    -286,
    -71,
    -274,
    -59
   ],
   "door": [
    -282,
    66,
    -65
   ],
   "door_facing": "west"
  },
  "pip_house": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_small_house_1",
   "rotation": "none",
   "act": "act1",
   "label": "Pip's Place",
   "level": 67,
   "origin": [
    -271,
    67,
    -69
   ],
   "footprint": {
    "x": [
     -271,
     -263
    ],
    "z": [
     -69,
     -61
    ]
   },
   "pad": [
    -273,
    -71,
    -261,
    -59
   ],
   "door": [
    -269,
    68,
    -65
   ],
   "door_facing": "west"
  },
  "granary": {
   "template": "kaisyn:village/exclusives/rustic/houses/rustic_barn_professions_1",
   "rotation": "none",
   "act": "act2",
   "label": "The Granary",
   "level": 69,
   "origin": [
    -338,
    68,
    -26
   ],
   "footprint": {
    "x": [
     -338,
     -328
    ],
    "z": [
     -26,
     -17
    ]
   },
   "pad": [
    -340,
    -28,
    -326,
    -15
   ],
   "door": [
    -337,
    70,
    -22
   ],
   "door_facing": "west"
  },
  "garden": {
   "template": "kaisyn:village/exclusives/classic/houses/classic_small_farm_1",
   "rotation": "none",
   "act": "act2",
   "label": "The Hedge Garden",
   "level": 65,
   "origin": [
    -314,
    65,
    -84
   ],
   "footprint": {
    "x": [
     -314,
     -305
    ],
    "z": [
     -84,
     -76
    ]
   },
   "pad": [
    -316,
    -86,
    -303,
    -74
   ]
  },
  "store": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_butcher_and_mason_1",
   "rotation": "none",
   "act": "act3",
   "label": "Oda's Store",
   "level": 67,
   "origin": [
    -296,
    67,
    -87
   ],
   "footprint": {
    "x": [
     -296,
     -286
    ],
    "z": [
     -87,
     -75
    ]
   },
   "pad": [
    -298,
    -89,
    -284,
    -73
   ],
   "door": [
    -290,
    68,
    -79
   ],
   "door_facing": "south"
  },
  "church": {
   "template": "kaisyn:village/exclusives/classic/houses/classic_church_1",
   "rotation": "none",
   "act": "act3",
   "label": "The Bell Tower",
   "level": 70,
   "origin": [
    -307,
    70,
    -68
   ],
   "footprint": {
    "x": [
     -307,
     -298
    ],
    "z": [
     -68,
     -62
    ]
   },
   "pad": [
    -309,
    -70,
    -296,
    -60
   ],
   "door": [
    -306,
    71,
    -65
   ],
   "door_facing": "east"
  },
  "town_hall": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_large_house_1",
   "rotation": "none",
   "act": "act5",
   "label": "The Town Hall",
   "level": 65,
   "origin": [
    -347,
    65,
    -78
   ],
   "footprint": {
    "x": [
     -347,
     -331
    ],
    "z": [
     -78,
     -66
    ]
   },
   "pad": [
    -349,
    -80,
    -329,
    -64
   ],
   "door": [
    -343,
    66,
    -72
   ],
   "door_facing": "west"
  },
  "newcomer_tess": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_medium_house_2",
   "rotation": "none",
   "act": "act5",
   "label": "Tess's House",
   "level": 69,
   "origin": [
    -282,
    69,
    -11
   ],
   "footprint": {
    "x": [
     -282,
     -271
    ],
    "z": [
     -11,
     1
    ]
   },
   "pad": [
    -284,
    -13,
    -269,
    3
   ],
   "door": [
    -278,
    70,
    -7
   ],
   "door_facing": "west"
  },
  "newcomer_mab": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_medium_house_3",
   "rotation": "none",
   "act": "act5",
   "label": "Mab's House",
   "level": 66,
   "origin": [
    -332,
    66,
    -10
   ],
   "footprint": {
    "x": [
     -332,
     -321
    ],
    "z": [
     -10,
     1
    ]
   },
   "pad": [
    -334,
    -12,
    -319,
    3
   ],
   "door": [
    -330,
    67,
    -6
   ],
   "door_facing": "west"
  },
  "newcomer_corin": {
   "template": "kaisyn:village/meadow_swiss/houses/meadow_medium_house_4",
   "rotation": "none",
   "act": "act5",
   "label": "Corin's House",
   "level": 66,
   "origin": [
    -252,
    66,
    -68
   ],
   "footprint": {
    "x": [
     -252,
     -241
    ],
    "z": [
     -68,
     -57
    ]
   },
   "pad": [
    -254,
    -70,
    -239,
    -55
   ],
   "door": [
    -250,
    67,
    -64
   ],
   "door_facing": "west"
  },
  "greenhouse": {
   "custom": true,
   "act": "act4",
   "label": "The Greenhouse",
   "level": 67,
   "footprint": {
    "x": [
     -334,
     -322
    ],
    "z": [
     -61,
     -53
    ]
   }
  },
  "bathhouse": {
   "custom": true,
   "act": "act4",
   "label": "The Bathhouse",
   "level": 67,
   "footprint": {
    "x": [
     -275,
     -267
    ],
    "z": [
     -30,
     -22
    ]
   }
  },
  "tobin_camp": {
   "custom": true,
   "act": "act1",
   "label": "The Copper Outcrop",
   "level": 66,
   "footprint": {
    "x": [
     -274,
     -266
    ],
    "z": [
     -82,
     -74
    ]
   }
  }
 },
 "doors": {
  "inn": [
   -279,
   68,
   -48
  ],
  "mill": [
   -342,
   68,
   -39
  ],
  "marnie_house": [
   -282,
   66,
   -65
  ],
  "pip_house": [
   -269,
   68,
   -65
  ],
  "granary": [
   -337,
   70,
   -22
  ],
  "store": [
   -290,
   68,
   -79
  ],
  "church": [
   -306,
   71,
   -65
  ],
  "town_hall": [
   -343,
   66,
   -72
  ],
  "newcomer_tess": [
   -278,
   70,
   -7
  ],
  "newcomer_mab": [
   -330,
   67,
   -6
  ],
  "newcomer_corin": [
   -250,
   67,
   -64
  ],
  "cottage": [
   -321,
   75,
   32
  ]
 },
 "lamps": [
  {
   "n": 1,
   "pos": [
    -314,
    70,
    -44
   ],
   "bare": false,
   "route": "finale"
  },
  {
   "n": 2,
   "pos": [
    -290,
    70,
    -44
   ],
   "bare": false,
   "route": "finale"
  },
  {
   "n": 3,
   "pos": [
    -302,
    70,
    -56
   ],
   "bare": false,
   "route": "finale"
  },
  {
   "n": 4,
   "pos": [
    -302,
    70,
    -32
   ],
   "bare": false,
   "route": "finale"
  },
  {
   "n": 5,
   "pos": [
    -304,
    70,
    -36
   ],
   "bare": false,
   "route": "q07"
  },
  {
   "n": 6,
   "pos": [
    -300,
    71,
    -28
   ],
   "bare": false,
   "route": "q07"
  },
  {
   "n": 7,
   "pos": [
    -300,
    70,
    -44
   ],
   "bare": false,
   "route": "q34"
  },
  {
   "n": 8,
   "pos": [
    -298,
    70,
    -44
   ],
   "bare": false,
   "route": "q34"
  },
  {
   "n": 9,
   "pos": [
    -303,
    70,
    -32
   ],
   "bare": false,
   "route": "q34"
  },
  {
   "n": 10,
   "pos": [
    -299,
    70,
    -32
   ],
   "bare": false,
   "route": "q34"
  },
  {
   "n": 11,
   "pos": [
    -303,
    70,
    -20
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 12,
   "pos": [
    -299,
    70,
    -20
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 13,
   "pos": [
    -304,
    71,
    -8
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 14,
   "pos": [
    -300,
    71,
    -8
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 15,
   "pos": [
    -305,
    72,
    3
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 16,
   "pos": [
    -301,
    71,
    3
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 17,
   "pos": [
    -305,
    74,
    15
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 18,
   "pos": [
    -301,
    74,
    15
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 19,
   "pos": [
    -306,
    76,
    27
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 20,
   "pos": [
    -302,
    76,
    27
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 21,
   "pos": [
    -307,
    76,
    39
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 22,
   "pos": [
    -303,
    78,
    39
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 23,
   "pos": [
    -318,
    71,
    -42
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 24,
   "pos": [
    -322,
    70,
    -41
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 25,
   "pos": [
    -326,
    71,
    -40
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 26,
   "pos": [
    -310,
    70,
    -43
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 27,
   "pos": [
    -298,
    70,
    -38
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 28,
   "pos": [
    -294,
    70,
    -34
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 29,
   "pos": [
    -290,
    70,
    -30
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 30,
   "pos": [
    -286,
    71,
    -26
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 31,
   "pos": [
    -282,
    70,
    -22
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 32,
   "pos": [
    -278,
    69,
    -18
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 33,
   "pos": [
    -306,
    70,
    -36
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 34,
   "pos": [
    -310,
    70,
    -32
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 35,
   "pos": [
    -314,
    71,
    -28
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 36,
   "pos": [
    -318,
    72,
    -24
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 37,
   "pos": [
    -322,
    73,
    -20
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 38,
   "pos": [
    -296,
    70,
    -52
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 39,
   "pos": [
    -292,
    70,
    -56
   ],
   "bare": false,
   "route": "q74"
  },
  {
   "n": 40,
   "pos": [
    -316,
    75,
    32
   ],
   "bare": true,
   "route": "q90"
  }
 ],
 "road_path": [
  [
   -299,
   69,
   -58
  ],
  [
   -299,
   69,
   -57
  ],
  [
   -301,
   69,
   -31
  ],
  [
   -301,
   69,
   -30
  ],
  [
   -301,
   69,
   -29
  ],
  [
   -301,
   70,
   -28
  ],
  [
   -301,
   70,
   -27
  ],
  [
   -301,
   70,
   -26
  ],
  [
   -301,
   70,
   -25
  ],
  [
   -301,
   69,
   -24
  ],
  [
   -301,
   69,
   -23
  ],
  [
   -301,
   69,
   -22
  ],
  [
   -301,
   69,
   -21
  ],
  [
   -301,
   69,
   -20
  ],
  [
   -301,
   69,
   -19
  ],
  [
   -301,
   69,
   -18
  ],
  [
   -302,
   70,
   -17
  ],
  [
   -302,
   70,
   -16
  ],
  [
   -302,
   70,
   -15
  ],
  [
   -302,
   70,
   -14
  ],
  [
   -302,
   70,
   -13
  ],
  [
   -302,
   70,
   -12
  ],
  [
   -302,
   70,
   -11
  ],
  [
   -302,
   70,
   -10
  ],
  [
   -302,
   70,
   -9
  ],
  [
   -302,
   70,
   -8
  ],
  [
   -302,
   70,
   -7
  ],
  [
   -302,
   70,
   -6
  ],
  [
   -302,
   70,
   -5
  ],
  [
   -302,
   70,
   -4
  ],
  [
   -302,
   70,
   -3
  ],
  [
   -302,
   70,
   -2
  ],
  [
   -302,
   70,
   -1
  ],
  [
   -303,
   71,
   0
  ],
  [
   -303,
   71,
   1
  ],
  [
   -303,
   71,
   2
  ],
  [
   -303,
   71,
   3
  ],
  [
   -303,
   71,
   4
  ],
  [
   -303,
   71,
   5
  ],
  [
   -303,
   72,
   6
  ],
  [
   -303,
   72,
   7
  ],
  [
   -303,
   72,
   8
  ],
  [
   -303,
   72,
   9
  ],
  [
   -303,
   72,
   10
  ],
  [
   -303,
   72,
   11
  ],
  [
   -303,
   73,
   12
  ],
  [
   -303,
   73,
   13
  ],
  [
   -303,
   73,
   14
  ],
  [
   -303,
   73,
   15
  ],
  [
   -304,
   73,
   16
  ],
  [
   -304,
   74,
   17
  ],
  [
   -304,
   74,
   18
  ],
  [
   -304,
   74,
   19
  ],
  [
   -304,
   74,
   20
  ],
  [
   -304,
   74,
   21
  ],
  [
   -304,
   74,
   22
  ],
  [
   -304,
   74,
   23
  ],
  [
   -304,
   74,
   24
  ],
  [
   -304,
   75,
   25
  ],
  [
   -304,
   75,
   26
  ],
  [
   -304,
   75,
   27
  ],
  [
   -304,
   75,
   28
  ],
  [
   -304,
   75,
   29
  ],
  [
   -304,
   76,
   30
  ],
  [
   -304,
   76,
   31
  ],
  [
   -305,
   76,
   32
  ],
  [
   -305,
   76,
   33
  ],
  [
   -305,
   76,
   34
  ],
  [
   -305,
   76,
   35
  ],
  [
   -305,
   76,
   36
  ],
  [
   -305,
   75,
   37
  ],
  [
   -305,
   75,
   38
  ],
  [
   -305,
   75,
   39
  ],
  [
   -305,
   75,
   40
  ],
  [
   -306,
   75,
   40
  ],
  [
   -307,
   75,
   40
  ],
  [
   -308,
   74,
   40
  ],
  [
   -309,
   74,
   40
  ],
  [
   -310,
   74,
   40
  ],
  [
   -311,
   74,
   40
  ],
  [
   -312,
   74,
   40
  ],
  [
   -313,
   74,
   40
  ],
  [
   -314,
   74,
   40
  ],
  [
   -315,
   74,
   40
  ],
  [
   -316,
   74,
   40
  ],
  [
   -317,
   74,
   40
  ],
  [
   -318,
   74,
   40
  ],
  [
   -319,
   74,
   40
  ]
 ],
 "signpost": [
  -299,
  71,
  -31
 ],
 "pier": [
  -302,
  71,
  -10
 ],
 "lake_centre": [
  -483,
  62,
  87
 ],
 "works": {
  "mark": [
   -268,
   54,
   -64
  ],
  "lever": [
   -268,
   56,
   -64
  ],
  "panel": [
   -268,
   56,
   -65
  ],
  "door": [
   -268,
   55,
   -70
  ],
  "shell": [
   -274,
   53,
   -70,
   -260,
   58,
   -56
  ],
  "plinth": [
   -268,
   54,
   -69
  ],
  "adit": {
   "mouth": [
    -268,
    65,
    -58
   ],
   "fall": [
    -268,
    55,
    -58,
    -267,
    64,
    -57
   ],
   "blocks": 40
  }
 },
 "marks": {
  "square": [
   -302,
   70,
   -44
  ],
  "board": [
   -302,
   70,
   -49
  ],
  "inn": [
   -279,
   68,
   -40
  ],
  "mill": [
   -329,
   67,
   -39
  ],
  "granary": [
   -338,
   70,
   -26
  ],
  "lake": [
   -302,
   71,
   -10
  ],
  "works": [
   -268,
   54,
   -64
  ],
  "greenhouse": [
   -328,
   68,
   -57
  ],
  "bathhouse": [
   -271,
   68,
   -26
  ],
  "echo_cave": [
   -268,
   30,
   -64
  ]
 },
 "npc_homes": {
  "inn": [
   -279,
   68,
   -48
  ],
  "mill": [
   -342,
   68,
   -39
  ],
  "marnie_house": [
   -282,
   66,
   -65
  ],
  "pip_house": [
   -269,
   68,
   -65
  ],
  "granary": [
   -337,
   70,
   -22
  ],
  "store": [
   -290,
   68,
   -79
  ],
  "church": [
   -306,
   71,
   -65
  ],
  "town_hall": [
   -343,
   66,
   -72
  ],
  "newcomer_tess": [
   -278,
   70,
   -7
  ],
  "newcomer_mab": [
   -330,
   67,
   -6
  ],
  "newcomer_corin": [
   -250,
   67,
   -64
  ]
 },
 "npc_stands": [
  {
   "group": "act1_mill",
   "pos": [
    -327,
    68,
    -42
   ]
  },
  {
   "group": "act1_marnie",
   "pos": [
    -284,
    66,
    -65
   ]
  },
  {
   "group": "act1_pip",
   "pos": [
    -271,
    68,
    -65
   ]
  },
  {
   "group": "act3_store",
   "pos": [
    -296,
    68,
    -82
   ]
  },
  {
   "group": "act1_tobin",
   "pos": [
    -270,
    67,
    -75
   ]
  }
 ],
 "cellar": {
  "stand": [
   -318,
   64,
   17
  ],
  "box": [
   -321,
   62,
   13,
   -314,
   67,
   21
  ],
  "door": [
   -318,
   64,
   13
  ],
  "chalk": [
   -319,
   65,
   14
  ],
  "chest": [
   -315,
   64,
   15
  ],
  "plinth": [
   -320,
   63,
   15
  ],
  "lock": [
   -318,
   64,
   12
  ],
  "gravel": [
   -318,
   63,
   21,
   -317,
   74,
   30
  ],
  "blocks": 40
 },
 "cellar_door": [
  -318,
  64,
  13
 ],
 "stake_socket": [
  -302,
  70,
  -46
 ],
 "lakefront": {
  "pier_waystone": [
   -294,
   71,
   -6
  ],
  "candles": [
   [
    -295,
    74,
    -2
   ],
   [
    -293,
    74,
    -2
   ],
   [
    -295,
    74,
    0
   ],
   [
    -293,
    74,
    0
   ],
   [
    -295,
    74,
    2
   ],
   [
    -293,
    74,
    2
   ]
  ],
  "campfire": [
   -298,
   71,
   -3
  ],
  "boat": [
   -299,
   71,
   0
  ],
  "water": [
   [
    -300,
    68,
    0
   ],
   [
    -286,
    70,
    14
   ]
  ]
 },
 "wisp_posts": [
  [
   -300,
   71,
   -30
  ],
  [
   -304,
   71,
   -24
  ],
  [
   -300,
   71,
   -18
  ],
  [
   -304,
   71,
   -12
  ]
 ],
 "town_waystone": [
  -302,
  70,
  -44
 ],
 "noticeboard": {
  "origin": [
   -302,
   70,
   -49
  ],
  "sign": [
   -301,
   73,
   -49
  ]
 }
}

console.info('[valley] valley_sites.js ok -- seed 5369984945557223422, anchor -302 69 -44, ' + global.valleySites.lamps.length + ' lamps, ' +
             Object.keys(global.valleySites.buildings).length + ' buildings')
