// =============================================================================
// valley_core.js — Little Kettle Valley: the spine.
//
// Owns:
//   * global.valley           the helper API every other valley script uses
//   * server.persistentData   anchor, home, lamps[], world stages, finale flags
//   * the FTB Teams auto-party (§9-A "the couple's team")
//   * the first-join handler (§2 premise, §12.5 first-join command block)
//   * the animal-crate / chicken-feed right-click handlers (§8 worked ex. 2)
//
// Engine notes verified against kubejs-forge-2001.6.5-build.26.jar:
//   * PlayerEvents has NO wakeUp/sleep event in this build. Sleep detection
//     lives in valley_checks.js as a slow-tick poll.
//   * There is no player.username. Use player.profile.name.
//   * server.persistentData is a CompoundTag (MinecraftServerMixin implements
//     WithPersistentData). Everything below stores FLAT primitive keys, because
//     nested CompoundTags returned by getCompound() are not reliably attached.
//   * There is no exposed scheduler binding, so delays are a tick queue here.
// =============================================================================

// -----------------------------------------------------------------------------
// 0. Tunables. Every anchor-relative offset in the pack lives here so the
//    checks and the finales can never disagree. [dx, dy, dz] from the Town
//    Anchor unless the name says HOME_.
// -----------------------------------------------------------------------------
const VALLEY = {
  // --- Named marks, anchor-relative ---------------------------------------
  // These come from the TOWN PLAN (town_plan.js, generated by
  // tools/scripts/plan_town.py from the installed structure NBTs), because the
  // mark and the building have to move together: `inn` is the tavern piece's
  // own campfire, `mill` is the yard block in front of the windmill's door,
  // `granary`/`greenhouse`/`bathhouse` are the corners the plan solved for.
  // KubeJS loads server_scripts alphabetically, so town_plan.js ("t") is
  // already loaded when this file ("v") runs. The literals below are the
  // fallback for a pack whose plan file has been removed, and are the only
  // marks nothing in the plan can move: the square, the board, the lake, the
  // Works and the echo cave.
  OFF: (typeof global.valleyTownPlan !== 'undefined' && global.valleyTownPlan.OFF)
    ? global.valleyTownPlan.OFF
    : {
        square:      [0, 1, 0],
        board:       [0, 1, -5],
        inn:         [23, 1, 2],
        mill:        [-27, 0, 5],
        granary:     [-36, 1, 18],
        lake:        [0, 1, 34],
        works:       [34, -6, -20],
        greenhouse:  [-24, 1, -13],
        bathhouse:   [29, 1, 16],
        echo_cave:   [34, -30, -20]
      },

  // --- Box sizes for "is the player standing in X" checks, in blocks -------
  BOX: {
    works:     [10, 6, 10],
    echo_cave: [8, 6, 8],
    cellar:    [7, 4, 7]
  },

  // Q5 wants "below the ruin floor"; Q55 wants "in the cellar, at the wall".
  HOME_CELLAR_Y: -3,          // Q5  : player.y <= home.y - 3
  HOME_DEEP_Y:   -6,          // Q55 : player.y <= home.y - 6
  HOME_PORCH:    [3, 0, 0],   // Q90 : the bare fortieth post

  // --- The Lantern Road. Anchor-relative post positions. -------------------
  // Act I's finale places LAMPS_FINALE itself. Q34 whitelists LAMPS_Q34, Q74
  // the rest. Everything actually placed is stored absolute in persistentData
  // and re-lit, all at once, by the Act IV lever.
  //
  // THE LAMP BLOCK. candlelight:lamp was wrong twice over: its blockstate
  // (letsdo-candlelight-forge-1.2.13.jar, assets/candlelight/blockstates/
  // lamp.json) carries ONLY `hanging`, so it has no lit form at all and the
  // Act IV lever could never turn it on; and its model is a 6x6 base, a 2x2
  // post and a cloth shade — a bedside table lamp sitting on the ground, not
  // a lamp post. createdeco:yellow_copper_lamp is a cage lamp with a real
  // lit=false|true, and copper is the valley's own metal.
  //
  // CageLampBlock#shouldBeLit is `inverted XOR redstone into the mounting
  // face`, and CageLampBlock#neighborChanged writes that answer straight back
  // over whatever `lit` a setblock wrote. So `lit` on its own does not hold:
  // a lamp that must STAY lit with no redstone on it is inverted=true,lit=true
  // and a dark one is inverted=false,lit=false. facing=up mounts it on the
  // block below, which is the fence post.
  //
  // A post is TWO blocks: LAMP_POST at the offset's own y, and the lamp at
  // y + LAMP_HEAD. Everything stored in persistentData.lamps[] is the LAMP's
  // position, never the post's, because that is what the Act IV sweep sets.
  // valley_finales.js mirrors these three strings as file-local constants
  // (they are baked into command arrays at script load) — change both.
  LAMP_BLOCK: 'createdeco:yellow_copper_lamp',
  LAMP_POST:  'minecraft:oak_fence',
  LAMP_HEAD:  1,
  LAMP_DARK:  'createdeco:yellow_copper_lamp[facing=up,inverted=false,lit=false]',
  LAMP_LIT:   'createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]',
  LAMP_TOLERANCE: 2,
  LAMPS_FINALE: [[-12,1,0],[12,1,0],[0,1,-12],[0,1,12]],
  // The two posts the datapack function valley:act1/square_path sets down
  // as Q7's reward. A setblock does not fire BlockEvents.placed, so they
  // are registered by the anchor listener alongside LAMPS_FINALE — without
  // that the Act IV lever would skip the first two posts on the road.
  LAMPS_Q07: [[-2,1,8],[2,1,16]],
  LAMPS_Q34: [[-16,1,2],[-20,1,3],[-24,1,4],[-8,1,1]],
  LAMPS_Q74: [
    [4,1,6],[8,1,10],[12,1,14],[16,1,18],[20,1,22],[24,1,26],
    [-4,1,8],[-8,1,12],[-12,1,16],[-16,1,20],[-20,1,24],
    [6,1,-8],[10,1,-12],[14,1,-16],[-6,1,-8],[-10,1,-12],[-14,1,-16]
  ],

  // --- Resident chat colours (§writer-brief rule 10) -----------------------
  // The quest book is the authority here: five of these nine used to disagree
  // with the tellraw colours in story/quests/*.json, so the same resident spoke
  // in a different colour depending on whether the line came from v.sayAll or
  // from a quest reward — and in a finale Marnie and Tobin came out identical.
  // Josie and Bram are both gray on purpose: Josie is chalk and paper and
  // almost never speaks aloud, and Bram's gray is established five times in the
  // book.
  VOICE: {
    Josie:  'gray',
    Marnie: 'light_purple',
    Bram:   'gray',
    Oda:    'gold',
    Nella:  'aqua',
    Halden: 'green',
    Tobin:  'yellow',
    Wisp:   'dark_green',
    Pip:    'red'
  },

  // --- The eight chain-closing quests, for Standing: Trusted (§5) ----------
  STANDING_CHAINS: ['q59', 'q60', 'q62', 'q63', 'q73', 'q75', 'q77', 'q85'],

  // --- Custom item ids used by the runtime handlers ------------------------
  ITEM: {
    letter: 'valley:letter',
    deed:   'valley:deed',
    kettle: 'herbalbrews:copper_tea_kettle'   // the Copper Kettle over the hearth
  }
}

const $AABB = Java.loadClass('net.minecraft.world.phys.AABB')

// -----------------------------------------------------------------------------
// 1. persistentData. Flat keys only — see the header note.
// -----------------------------------------------------------------------------
function pdata() {
  let s = global.valleyServer
  return s ? s.persistentData : null
}

function pdGet(key, fallback) {
  let d = pdata()
  if (!d || !d.contains(key)) return fallback
  return d.getString(key)
}

function pdPut(key, value) {
  let d = pdata()
  if (d) d.putString(key, String(value))
}

function pdFlag(key) {
  let d = pdata()
  return !!(d && d.contains(key))
}

function pdSetFlag(key) {
  let d = pdata()
  if (d) d.putString(key, '1')
}

function posToStr(p) { return p[0] + ',' + p[1] + ',' + p[2] }

function strToPos(s) {
  if (!s) return null
  let parts = String(s).split(',')
  if (parts.length !== 3) return null
  let x = parseInt(parts[0], 10), y = parseInt(parts[1], 10), z = parseInt(parts[2], 10)
  if (isNaN(x) || isNaN(y) || isNaN(z)) return null
  return [x, y, z]
}

// -----------------------------------------------------------------------------
// 2. The delay queue. Replaces `/schedule function`, which needs a datapack
//    function we do not ship. Drained by the tick handler at the bottom; the
//    array is empty except during a finale, so the cost is one length check.
// -----------------------------------------------------------------------------
const valleyPending = []

function valleyDelay(ticks, fn) {
  valleyPending.push({ at: global.valleyTick + ticks, fn: fn })
}

// -----------------------------------------------------------------------------
// 3. The public API. Everything in valley_gates / valley_checks /
//    valley_finales, and every act writer's KubeJS-facing assumption, goes
//    through this object.
// -----------------------------------------------------------------------------
global.valley = {

  C: VALLEY,

  // ---- server handle ------------------------------------------------------
  server: function () { return global.valleyServer },

  // ---- Town Anchor (Q7). Returns [x,y,z] or null. -------------------------
  anchor: function () { return strToPos(pdGet('valley_anchor', null)) },

  setAnchor: function (x, y, z) {
    pdPut('valley_anchor', posToStr([x, y, z]))
    console.info('[valley] Town Anchor set to ' + x + ' ' + y + ' ' + z)
  },

  // ---- The Homestead waystone (Q2). Returns [x,y,z] or null. --------------
  home: function () { return strToPos(pdGet('valley_home', null)) },

  setHome: function (x, y, z) {
    pdPut('valley_home', posToStr([x, y, z]))
    console.info('[valley] Home set to ' + x + ' ' + y + ' ' + z)
  },

  // ---- The ruined Kettle farm's hearthstone (§3 "the one exception").
  //      Placed at first join by placeRuin() below. Returns [x,y,z] or null.
  ruin: function () { return strToPos(pdGet('valley_ruin', null)) },

  setRuin: function (x, y, z) {
    pdPut('valley_ruin', posToStr([x, y, z]))
    console.info('[valley] Kettle ruin hearthstone at ' + x + ' ' + y + ' ' + z)
  },

  // ---- anchor + offset -> absolute [x,y,z]. Null if no anchor. ------------
  offset: function (off) {
    let a = global.valley.anchor()
    if (!a) return null
    return [a[0] + off[0], a[1] + off[1], a[2] + off[2]]
  },

  // ---- Named mark by key from VALLEY.OFF ---------------------------------
  mark: function (name) {
    let off = VALLEY.OFF[name]
    return off ? global.valley.offset(off) : null
  },

  // ---- Complete a quest for the player's TEAM (§P2). ---------------------
  // key is an outline key: 'q07'. Silently no-ops if the compiler has not
  // emitted that key into _quest_ids.js yet, so a half-built pack still runs.
  complete: function (player, key) {
    let ids = global.valleyQuestIds || {}
    let id = ids[key]
    if (!id) {
      if (!global.valleyMissingWarned) global.valleyMissingWarned = {}
      if (!global.valleyMissingWarned[key]) {
        global.valleyMissingWarned[key] = true
        console.warn('[valley] no quest id for "' + key + '" in _quest_ids.js — skipping completion')
      }
      return false
    }
    let s = global.valleyServer
    if (!s) return false
    s.runCommandSilent('ftbquests change_progress ' + global.valley.pname(player) +
                       ' complete ' + global.valley.cmdId(id))
    return true
  },

  // ---- A quest id in the form /ftbquests will actually parse. -------------
  // FTB Quests reads its object argument with QuestObjectBase.parseCodeString,
  // which is Long.parseLong(s, 16) — SIGNED. Any id whose top bit is set (a
  // first hex digit of 8-F) overflows, the NumberFormatException is swallowed,
  // and the argument comes back as 0, so the command answers "Invalid Object
  // ID" and completes nothing. 66 of this pack's 126 quest ids sit in that
  // half of the space, which silently disabled fourteen of the twenty-four
  // KubeJS auto-completions — q01, q02, q65 and q71 among them.
  //
  // compile_quests.py now clears bit 63 when it derives an id, so nothing the
  // compiler emits reaches this branch any more — but the same id also has to
  // survive being read back out of a file someone hand-edited, and a silent
  // no-op is the worst possible failure here. The same long written as a
  // NEGATIVE hex literal parses, and '-' is legal in an unquoted Brigadier
  // string, so that is the fallback. Arithmetic is nibble by nibble because a
  // 64-bit id does not survive a JS double.
  cmdId: function (hex) {
    let h = String(hex).toUpperCase()
    if (h.length < 16 || '89ABCDEF'.indexOf(h.charAt(0)) < 0) return h
    let d = []
    for (let i = 0; i < 16; i++) d.push(15 - parseInt(h.charAt(i), 16))
    let carry = 1
    for (let i = 15; i >= 0; i--) {
      let v = d[i] + carry
      d[i] = v & 15
      carry = v >> 4
    }
    let out = ''
    for (let i = 0; i < 16; i++) out += '0123456789ABCDEF'.charAt(d[i])
    out = out.replace(/^0+/, '')
    return '-' + (out === '' ? '0' : out)
  },

  // ---- The player's login name. There is no player.username in 2001.6.5. --
  pname: function (player) { return player.profile.name },

  // ---- Give a KubeJS stage to every ONLINE member of a team. -------------
  // Stages are per player (§naming contract), so a team-wide grant is a loop.
  // `team` may be an FTB team object, or null for "everyone online".
  stageAll: function (team, stage) {
    let s = global.valleyServer
    if (!s) return
    s.players.forEach(p => {
      if (team) {
        // p.team only exists when the FTB Teams integration is present; if the
        // lookup fails for any reason we fall back to "everyone online", which
        // is correct for a one-team world and harmless for two.
        try { if (p.team && String(p.team.id) !== String(team.id)) return } catch (err) { /* ignore */ }
      }
      if (!p.stages.has(stage)) p.stages.add(stage)
    })
  },

  // ---- One resident line, in that resident's colour (§writer-brief 10). ---
  // Built as tellraw JSON so nothing depends on a Component builder overload.
  say: function (player, who, text) {
    let colour = VALLEY.VOICE[who] || 'white'
    let json = [
      { text: who + ': ', color: colour, bold: false },
      { text: text, color: 'white', italic: true }
    ]
    let s = global.valleyServer
    if (!s) return
    s.runCommandSilent('tellraw ' + global.valley.pname(player) + ' ' + JSON.stringify(json))
  },

  // ---- A resident's greeting line, picked out of that resident's pool. ----
  //
  // Every resident used to have exactly two lines for the whole sixteen-hour
  // pack — one before their arc closed, one after — wired as a pair of
  // /info_message actions on the NPC. /info_message renders as a screen title,
  // which is why the generator refuses a Cmd over 120 characters or containing
  // a double quote; that ceiling is what kept the town to two sentences each.
  //
  // So the NPC now runs `/valley greet <key> <before|after> @initiator` and the
  // lines live in valley_greetings.js (GENERATED from story/npcs.json). The
  // scoreboard condition that chooses before/after is unchanged and still lives
  // on the Easy NPC action, so the arc gating is the same verified mechanism.
  //
  // Rotation is by world day plus a hash of the player's name: stable within a
  // day (clicking Marnie twice in a row does not shuffle), different from one
  // day to the next, and different between two players standing side by side.
  greet: function (playerName, key, phase) {
    let pools = global.valleyGreetings
    if (!pools) return
    let entry = pools[key]
    if (!entry) { console.warn('[valley] /valley greet: unknown resident ' + key); return }
    let pool = (phase === 'after' && entry.after) ? entry.after : entry.before
    if (!pool || !pool.length) return

    let s = global.valleyServer
    if (!s) return
    let player = null
    try { player = s.getPlayer(playerName) } catch (err) { player = null }
    if (!player) return

    let day = 0
    try { day = Math.floor(s.overworld().getDayTime() / 24000) } catch (err) { day = 0 }
    let h = 0
    let n = String(playerName)
    for (let i = 0; i < n.length; i++) h = (h * 31 + n.charCodeAt(i)) % 100003
    let idx = (day + h) % pool.length
    if (idx < 0) idx += pool.length

    global.valley.say(player, entry.name, pool[idx])
  },

  // ---- Same line, to everyone. Used by the finales. ----------------------
  sayAll: function (who, text) {
    let colour = VALLEY.VOICE[who] || 'white'
    let json = [
      { text: who + ': ', color: colour },
      { text: text, color: 'white', italic: true }
    ]
    let s = global.valleyServer
    if (s) s.runCommandSilent('tellraw @a ' + JSON.stringify(json))
  },

  // ---- World stages. There is no GameStages mod; a world stage is a flag in
  //      persistentData (§9-F "world stages vs team stages"). -------------
  hasWorldStage: function (id) { return pdFlag('valley_ws_' + id) },
  addWorldStage: function (id) {
    if (!pdFlag('valley_ws_' + id)) {
      pdSetFlag('valley_ws_' + id)
      console.info('[valley] world stage granted: ' + id)
    }
  },

  // ---- The Lantern Road list. Absolute coords, CSV in persistentData. ----
  lamps: function () {
    let raw = pdGet('valley_lamps', '')
    if (!raw) return []
    return String(raw).split(';').filter(s => s.length > 0).map(strToPos).filter(p => p)
  },

  addLamp: function (x, y, z) {
    let list = global.valley.lamps()
    for (let i = 0; i < list.length; i++) {
      if (list[i][0] === x && list[i][1] === y && list[i][2] === z) return false
    }
    let raw = pdGet('valley_lamps', '')
    pdPut('valley_lamps', raw ? raw + ';' + posToStr([x, y, z]) : posToStr([x, y, z]))
    return true
  },

  // ---- Finale idempotency (§P7). ----------------------------------------
  finaleDone: function (act) { return pdFlag('valley_finale_' + act) },
  markFinale: function (act) { pdSetFlag('valley_finale_' + act) },

  // ==========================================================================
  // Standing: Trusted (§5, §12.3) — Q86's second condition.
  //
  // Standing is "how many of the eight named resident chains this TEAM has
  // closed". The authoritative record is a ledger of flags in
  // server.persistentData, written by a silent command reward on each of the
  // eight closing quests:
  //     /valley standing <key> {team}
  // CommandReward#claim substitutes only @p, {x} {y} {z}, {team}, {quest} and
  // {chapter}. There is NO {long_team_id}; {team} is the FTB Teams SHORT TEAM
  // NAME, a plain string. The ledger is therefore keyed on that string, and
  // teamId() below resolves the same short name for a caller with no argument.
  //
  // standingApiClosed() below is a top-up, not the source of truth: it reads
  // the FTB XMod Compat KubeJS binding when that binding exists, so a chain
  // closed before this ledger shipped (or claimed while the reward failed)
  // still counts. It returns null the moment anything about the binding is
  // not what we expect, and the ledger carries on alone.
  // ==========================================================================

  STANDING_REQUIRED: 6,

  // The eight chain keys, in story order.
  standingChains: function () { return VALLEY.STANDING_CHAINS.slice(0) },

  // The FTB team SHORT NAME for this player, or their login name when FTB
  // Teams is not answering. This is what {team} expands to in a command
  // reward, so both halves of the ledger agree on one key.
  teamId: function (player) {
    try {
      let t = player ? player.team : null
      if (t) {
        let n = t.shortName
        if (!n) { try { n = t.getShortName() } catch (e2) { n = null } }
        if (!n) n = t.name
        if (n) return String(n)
      }
    } catch (err) { /* no FTB Teams integration; fall through */ }
    return player ? global.valley.pname(player) : 'server'
  },

  // The FTB Teams short name for this player, or NULL when FTB Teams is not
  // answering. teamId() above falls back to the LOGIN NAME on purpose, which
  // is right for a ledger key and wrong for anything that has to be handed
  // back to `ftbteams party join` — hence this second, strict reader.
  teamShortName: function (player) {
    try {
      let t = player ? player.team : null
      if (!t) return null
      let n = t.shortName
      if (!n) { try { n = t.getShortName() } catch (e2) { n = null } }
      if (!n) n = t.name
      return n ? String(n) : null
    } catch (err) { return null }
  },

  // persistentData is flat primitives only (see the header note), so the team
  // and the quest key are folded into the key name.
  standingSlot: function (teamId, questKey) {
    return 'valley_standing_' + String(teamId).replace(/[^A-Za-z0-9]/g, '') + '_' + questKey
  },

  // Returns true the first time this chain is recorded for this team.
  recordStanding: function (teamId, questKey) {
    if (VALLEY.STANDING_CHAINS.indexOf(questKey) === -1) return false
    let slot = global.valley.standingSlot(teamId, questKey)
    if (pdFlag(slot)) return false
    pdSetFlag(slot)
    console.info('[valley] standing: ' + questKey + ' recorded for team ' + teamId)
    return true
  },

  standingClosed: function (teamId) {
    return VALLEY.STANDING_CHAINS.filter(k => pdFlag(global.valley.standingSlot(teamId, k)))
  },

  standingCount: function (teamId) { return global.valley.standingClosed(teamId).length },

  standingGranted: function (teamId) {
    return pdFlag('valley_standing_done_' + String(teamId).replace(/[^A-Za-z0-9]/g, ''))
  },

  markStandingGranted: function (teamId) {
    pdSetFlag('valley_standing_done_' + String(teamId).replace(/[^A-Za-z0-9]/g, ''))
  },

  // Which of the eight FTB Quests itself says are complete for this player's
  // team, or null when the binding is absent or shaped differently.
  //
  // Binding verified in ftb-xmod-compat-forge-2.1.3.jar:
  //   KubeJSIntegration#registerBindings  -> add("FTBQuests", FTBQuestsKubeJSWrapper.INSTANCE)
  //   FTBQuestsKubeJSWrapper#getServerDataFromPlayer(Player)
  //                                       -> FTBQuestsKubeJSPlayerData
  //   FTBQuestsKubeJSTeamData#isCompleted(Object) -> boolean
  //     (resolves the argument through BaseQuestFile#getID, which parses the
  //      16-char hex ids _quest_ids.js already stores)
  standingApiClosed: function (player) {
    if (typeof FTBQuests === 'undefined' || !player) return null
    let ids = global.valleyQuestIds || {}
    let out = []
    try {
      let data = FTBQuests.getServerDataFromPlayer(player)
      if (!data) return null
      for (let i = 0; i < VALLEY.STANDING_CHAINS.length; i++) {
        let k = VALLEY.STANDING_CHAINS[i]
        let id = ids[k]
        if (!id) continue
        if (data.isCompleted(id)) out.push(k)
      }
    } catch (err) {
      if (!global.valleyStandingApiWarned) {
        global.valleyStandingApiWarned = true
        console.warn('[valley] FTBQuests binding unusable for Standing (' + err + '); ' +
                     'the command-reward ledger is authoritative and unaffected.')
      }
      return null
    }
    return out
  },

  // ---- Generic once-per-TEAM latch, used by the checks. ------------------
  // A checkmark quest is completed per FTB Teams PARTY, so the latch that
  // stops it re-firing has to be per party too. A flat world-level latch
  // (which is what this was) let the first party through and then hard-stuck
  // the second one on every KubeJS-completed quest — twenty of them, starting
  // at Q2. The slot name folds in the same sanitised short name the Standing
  // ledger uses, because persistentData is flat primitives only.
  //
  // `team` omitted means world-level, which is exactly what the genuinely
  // one-per-world flags want (world_opened, ruin_placed).
  onceSlot: function (key, team) {
    let t = team ? String(team).replace(/[^A-Za-z0-9]/g, '') : 'w'
    return 'valley_once_' + t + '_' + key
  },
  once: function (key, team) {
    let k = global.valley.onceSlot(key, team)
    if (pdFlag(k)) return false
    pdSetFlag(k)
    return true
  },
  isDone: function (key, team) { return pdFlag(global.valley.onceSlot(key, team)) },

  // ---- Delay, in ticks. ---------------------------------------------------
  delay: valleyDelay,

  // ---- Raw persistent storage, for the checks' per-player baselines. ------
  get: function (key, fallback) { return pdGet(key, fallback) },
  set: function (key, value) { pdPut(key, value) },

  // ---- Entities of a type inside a box centred on [x,y,z]. ---------------
  countNear: function (level, pos, radius, typePrefix) {
    let box = new $AABB(
      pos[0] - radius, pos[1] - radius, pos[2] - radius,
      pos[0] + radius, pos[1] + radius, pos[2] + radius
    )
    let n = 0
    level.getEntitiesWithin(box).forEach(e => {
      if (String(e.type).indexOf(typePrefix) === 0) n++
    })
    return n
  },

  // ---- Is this player inside the box [centre, size]? ---------------------
  inBox: function (player, centre, size) {
    if (!centre) return false
    return Math.abs(player.x - centre[0]) <= size[0] &&
           Math.abs(player.y - centre[1]) <= size[1] &&
           Math.abs(player.z - centre[2]) <= size[2]
  },

  // ---- Horizontal distance, for "within N of Home" checks. ---------------
  flatDist: function (player, pos) {
    let dx = player.x - pos[0], dz = player.z - pos[2]
    return Math.sqrt(dx * dx + dz * dz)
  }
}

// =============================================================================
// 4. Server lifecycle
// =============================================================================
global.valleyTick = 0

ServerEvents.loaded(event => {
  global.valleyServer = event.server
  global.valleyTick = 0
  valleyPending.length = 0

  // §P6 — the two counters are bossbars. Re-issued on every load; `add` on an
  // existing bar is a harmless failure.
  let s = event.server
  s.runCommandSilent('bossbar add valley:lamps {"text":"Lantern Road","color":"gold"}')
  s.runCommandSilent('bossbar set valley:lamps max 40')
  s.runCommandSilent('bossbar set valley:lamps players @a')
  s.runCommandSilent('bossbar add valley:folk {"text":"Residents","color":"green"}')
  s.runCommandSilent('bossbar set valley:folk max 15')
  s.runCommandSilent('bossbar set valley:folk players @a')

  let a = global.valley.anchor()
  console.info('[valley] core loaded. Anchor: ' + (a ? a.join(' ') : 'not set yet'))
})

ServerEvents.unloaded(event => {
  global.valleyServer = null
  valleyPending.length = 0
})

// The one shared tick handler for the delay queue. valley_checks.js keeps its
// own slow-tick poll; this one only drains scheduled finale steps.
ServerEvents.tick(event => {
  global.valleyTick++
  if (valleyPending.length === 0) return
  for (let i = valleyPending.length - 1; i >= 0; i--) {
    if (valleyPending[i].at <= global.valleyTick) {
      let job = valleyPending.splice(i, 1)[0]
      try { job.fn(event.server) } catch (err) { console.error('[valley] delayed step failed: ' + err) }
    }
  }
})

// =============================================================================
// 5. Login: the FTB Teams auto-party, then the first-join handler.
// =============================================================================
PlayerEvents.loggedIn(event => {
  let player = event.entity
  let server = global.valleyServer || player.server
  if (!server) return
  let name = global.valley.pname(player)

  // ---- §9-A: everybody lands on ONE party. Guarded by the per-player stage
  // cozy_party; skipped entirely for anyone holding solo_team (§9-B, the
  // second letter / a player who wants their own book).
  //
  // `ftbteams party join Cozy` can never work: the join argument is a party
  // ID or short name, not the display name, and every player who ran the old
  // pair of commands ended up on their OWN party that was also displayed as
  // "Cozy". Both commands are runCommandSilent, so nothing said so — and FTB
  // Quests then keyed progress off a different team id per player.
  //
  // So: the FIRST player through creates the party and we write down the real
  // short name FTB Teams gave it. Everyone after that joins THAT string, and
  // only falls through to creating one if the join left them where they were.
  if (!player.stages.has('cozy_party') && !player.stages.has('solo_team')) {
    player.stages.add('cozy_party')
    valleyJoinParty(server, player, name)
  }

  // ---- §12.5 first-join block. Per player, once.
  if (!player.stages.has('first_join')) {
    player.stages.add('first_join')
    valleyFirstJoin(server, player, name)
  }

  // Re-attach the bossbars for this player.
  server.runCommandSilent('bossbar set valley:lamps players @a')
  server.runCommandSilent('bossbar set valley:folk players @a')
})

// The party dance. Split out of loggedIn so the retry can run a tick later:
// FTB Teams applies a join/create on the command's own tick, so player.team is
// still the old value at the moment the command returns.
function valleyJoinParty(server, player, name) {
  let stored = pdGet('valley_team', null)

  if (stored) {
    server.runCommandSilent('execute as ' + name + ' run ftbteams party join ' + stored)
  }

  valleyDelay(1, s => {
    let now = global.valley.teamShortName(player)
    // Already on the pack's party — nothing more to do.
    if (stored && now && now === stored) {
      console.info('[valley] ' + name + ' joined party ' + stored)
      return
    }
    // No party recorded yet, or the join did not take: make one and record
    // whatever short name FTB Teams actually assigned it.
    s.runCommandSilent('execute as ' + name + ' run ftbteams party create Cozy')
    s.runCommandSilent('execute as ' + name + ' run ftbteams party settings free_to_join true')
    valleyDelay(1, s2 => {
      let made = global.valley.teamShortName(player)
      if (!made) {
        console.warn('[valley] FTB Teams did not report a party for ' + name +
                     '; quest progress will be keyed on their login name.')
        return
      }
      if (!pdGet('valley_team', null)) {
        pdPut('valley_team', made)
        console.info('[valley] the pack party is "' + made + '" (created by ' + name + ')')
      } else if (made !== pdGet('valley_team', null)) {
        console.warn('[valley] ' + name + ' is on party "' + made + '", not "' +
                     pdGet('valley_team', null) + '". They keep their own quest book.')
      }
    })
  })
}

// =============================================================================
// FIX: the ruined Kettle farm (§3 "The one exception, and it matters", §12.1
// C5, §12.5 `function valley:setup/place_ruin`).
//
// The premise, Q1's map and Q2's instruction all send the player to a house
// that had no worldgen entry, no structure NBT and no placement anywhere in
// the pack — the only chimney in the files was the one Q2's REWARD builds.
// This puts it on the ground before Q2 asks for it, 48-64 blocks from spawn on
// a levelled pad, and lays a lit path to it so "go and find it" is a walk and
// never a search.
// =============================================================================

// Eight bearings, north first, so the path reads the same way in most worlds.
const RUIN_BEARINGS = [
  [0, -1], [1, -1], [-1, -1], [1, 0], [-1, 0], [1, 1], [-1, 1], [0, 1]
]
const RUIN_DIST = [56, 64, 48]
const RUIN_NAME = { '0,-1': 'north', '1,-1': 'north-east', '-1,-1': 'north-west',
                    '1,0': 'east', '-1,0': 'west', '1,1': 'south-east',
                    '-1,1': 'south-west', '0,1': 'south' }

// Blocks that are "on top of" the ground rather than the ground itself.
const RUIN_SKIP = {
  'minecraft:air': 1, 'minecraft:cave_air': 1, 'minecraft:void_air': 1,
  'minecraft:snow': 1, 'minecraft:grass': 1, 'minecraft:tall_grass': 1,
  'minecraft:fern': 1, 'minecraft:large_fern': 1, 'minecraft:dead_bush': 1,
  'minecraft:vine': 1, 'minecraft:sugar_cane': 1, 'minecraft:seagrass': 1,
  'minecraft:tall_seagrass': 1
}

// Top solid Y at (x,z), or -1. Skips foliage and treetops so a spot under an
// oak is still "the ground" and not "y+7 in the canopy".
function ruinSurface(level, x, z) {
  for (let y = 200; y > 2; y--) {
    let id = String(level.getBlock(x, y, z).id)
    if (RUIN_SKIP[id]) continue
    if (id.indexOf('leaves') >= 0 || id.indexOf('_log') >= 0 ||
        id.indexOf('_wood') >= 0 || id.indexOf('mushroom_block') >= 0) continue
    if (id === 'minecraft:water' || id === 'minecraft:lava' ||
        id === 'minecraft:ice' || id === 'minecraft:frosted_ice') return -1
    return y
  }
  return -1
}

// A site is good if the ground is found at the centre and at all four corners
// of the pad, and the pad is not a cliff.
function ruinSiteOk(level, x, z) {
  let c = ruinSurface(level, x, z)
  if (c < 40 || c > 180) return -1
  let probes = [[-8, -8], [8, -8], [-8, 8], [8, 8], [0, -8], [0, 8]]
  for (let i = 0; i < probes.length; i++) {
    let h = ruinSurface(level, x + probes[i][0], z + probes[i][1])
    if (h < 0) return -1
    if (Math.abs(h - c) > 6) return -1
  }
  return c
}

// The lit path from spawn to the gate. One setblock per step, each at that
// step's own surface, so it drapes over the terrain instead of cutting it.
function ruinPath(server, level, from, to) {
  let dx = to[0] - from[0], dz = to[2] - from[2]
  let steps = Math.max(Math.abs(dx), Math.abs(dz))
  if (steps < 1) return
  for (let i = 0; i <= steps; i++) {
    let x = Math.round(from[0] + dx * i / steps)
    let z = Math.round(from[2] + dz * i / steps)
    let y = ruinSurface(level, x, z)
    if (y < 0) continue
    // three wide, across whichever axis the path is running along
    let side = Math.abs(dx) >= Math.abs(dz) ? [0, 1] : [1, 0]
    for (let k = -1; k <= 1; k++) {
      let px = x + side[0] * k, pz = z + side[1] * k
      let py = (k === 0) ? y : ruinSurface(level, px, pz)
      if (py < 0) continue
      server.runCommandSilent('setblock ' + px + ' ' + py + ' ' + pz +
        (k === 0 ? ' minecraft:dirt_path' : ' minecraft:gravel'))
      server.runCommandSilent('setblock ' + px + ' ' + (py + 1) + ' ' + pz + ' minecraft:air')
    }
    // a lantern on a post every eight blocks, on alternating sides
    if (i > 0 && i % 8 === 0) {
      let k = (i % 16 === 0) ? 2 : -2
      let px = x + side[0] * k, pz = z + side[1] * k
      let py = ruinSurface(level, px, pz)
      if (py < 0) continue
      server.runCommandSilent('setblock ' + px + ' ' + (py + 1) + ' ' + pz + ' minecraft:oak_fence')
      server.runCommandSilent('setblock ' + px + ' ' + (py + 2) + ' ' + pz + ' minecraft:lantern[hanging=false]')
    }
  }
}

// Returns the bearing name the path runs in, or null if nothing was placed.
function placeRuin(server, player) {
  let level = player.level
  let sx = Math.floor(player.x), sy = Math.floor(player.y), sz = Math.floor(player.z)

  let best = null
  for (let d = 0; d < RUIN_DIST.length && !best; d++) {
    for (let b = 0; b < RUIN_BEARINGS.length && !best; b++) {
      let bear = RUIN_BEARINGS[b]
      let len = RUIN_DIST[d]
      let norm = (bear[0] !== 0 && bear[1] !== 0) ? 0.7071 : 1
      let x = sx + Math.round(bear[0] * len * norm)
      let z = sz + Math.round(bear[1] * len * norm)
      let y = ruinSiteOk(level, x, z)
      if (y > 0) best = { x: x, y: y, z: z, bearing: bear, dist: len }
    }
  }
  // Nothing passed — an island, a swamp, a mountain. Take due north at 56 and
  // let the pad fill do the levelling; a ruin on a filled pad beats no ruin.
  if (!best) {
    let x = sx, z = sz - 56
    let y = ruinSurface(level, x, z)
    if (y < 0) y = sy
    best = { x: x, y: y, z: z, bearing: [0, -1], dist: 56 }
    console.warn('[valley] no clean ruin site found; forcing one due north of spawn.')
  }

  // The hearthstone IS the ground the pad is cut to: valley:setup/place_ruin
  // lays its pad top course at ~0 and drops the ruin's floor layer on it, so
  // the farm reads flush with the terrain the lit path walks in over instead
  // of standing on a one-block plinth.
  let hx = best.x, hy = best.y, hz = best.z
  server.runCommandSilent(
    'execute positioned ' + hx + ' ' + hy + ' ' + hz + ' run function valley:setup/place_ruin')
  global.valley.setRuin(hx, hy, hz)
  ruinPath(server, level, [sx, sy, sz], [hx, hy, hz])
  return RUIN_NAME[best.bearing[0] + ',' + best.bearing[1]] || 'north'
}

// The four pages of Josie's Letter. Q1's one instruction is "read all four
// pages", and valley:letter was a plain KubeJS item with a rarity tint and no
// right-click behaviour — clicking it did nothing, there were no pages, and the
// quest was ticked the moment it landed in her bag. A vanilla written_book opens
// the real book screen on the first click: four pages, arrows, no mod involved
// and no NBT key we have to guess right.
const LETTER_PAGES = [
  "If you're reading this I'm dead and the valley is cold. Only one of those is your problem.\n\nThe farm is yours. So is the mess.",
  "Fifteen people stayed. Marnie keeps an inn with no guests. Bram keeps a mill with a snapped axle. Oda has kept the ledger of an empty shop for eleven years.\n\nThat is not stubbornness. That is a town waiting.",
  "Forty lamp posts stand along that road and not one of them is lit. That is the whole job. Nobody is going to thank you for it until they do.\n\nForty lamps. Fifteen people. One winter that nobody leaves.",
  "The map, then. Follow the lit path from where you woke up. It ends at a chimney with three walls still standing.\n\nPut the waystone on the flat grey hearthstone and name it Home. Start from the part that held.\n\n\u2014 Josie Kettle"
]

// Built fresh per player: an ItemStack handed to two people is one stack.
function josieLetter() {
  try {
    // title / author / pages are exactly what WrittenBookItem.makeSureTagIsValid
    // requires (string, string, list). `generation` is deliberately absent: a JS
    // number comes through the KubeJS NBT converter as a DOUBLE, and while
    // getInt() survives that, an un-written key reads as 0 with no surprises.
    return Item.of('minecraft:written_book', {
      title: "Josie's Letter",
      author: 'Josie Kettle',
      pages: LETTER_PAGES.map(page => JSON.stringify({ text: page }))
    })
  } catch (err) {
    // Never let the letter cost somebody their first join. The keepsake item is
    // still registered and Q1's task is a checkmark she can tick by hand.
    console.error('[valley] could not build the written letter (' + err + '); ' +
                  'handing over valley:letter instead.')
    return Item.of(VALLEY.ITEM.letter)
  }
}

function valleyFirstJoin(server, player, name) {
  // The letter, the deed and the kettle. Q1's task is READING the letter, which
  // valley_checks.js ticks off the right-click that opens the book.
  player.give(josieLetter())
  player.give(Item.of(VALLEY.ITEM.deed))
  player.give(Item.of(VALLEY.ITEM.kettle))

  // Title card. Exactly the words in §2.
  server.runCommandSilent('title ' + name + ' times 20 90 30')
  server.runCommandSilent('title ' + name + ' subtitle ' +
    JSON.stringify({ text: 'Spring, Year One.', color: 'gray', italic: true }))
  server.runCommandSilent('title ' + name + ' title ' +
    JSON.stringify({ text: 'LITTLE KETTLE VALLEY', color: 'gold', bold: true }))
  // `~ ~ ~` resolves against the COMMAND SOURCE, and runCommandSilent runs as
  // the server (0 0 0, overworld) — so the sound has to be run `execute at`
  // the player or nobody hears it.
  server.runCommandSilent('execute at ' + name + ' run playsound minecraft:block.note_block.chime master ' + name + ' ~ ~ ~ 1 0.8')

  // §3 "The one exception, and it matters": the ruined Kettle farm goes on the
  // ground NOW, before Q1's map and Q2's instruction send her to it. Once per
  // world; the bearing is stored so a player joining later gets the same
  // direction and walks the same path.
  let where = pdGet('valley_ruin_bearing', null)
  if (global.valley.once('ruin_placed')) {
    try {
      where = placeRuin(server, player)
      if (where) pdPut('valley_ruin_bearing', where)
    } catch (err) {
      console.error('[valley] could not place the Kettle ruin: ' + err)
    }
  }
  let ruinPos = global.valley.ruin()

  // The premise, then the destination line, verbatim (writer-brief rule 3).
  let lines = [
    [{ text: 'You inherited the old Kettle farm from a great-aunt you barely remember — ', color: 'white' },
     { text: 'Josie Kettle', color: 'gold' },
     { text: ', who kept the lights on in this valley long after everyone else stopped trying.', color: 'white' }],
    [{ text: 'A chimney, three walls, a bed frame, and a copper kettle over a cold hearth. Outside: an inn with no innkeeper, a mill with a snapped axle, a store with the shutters down, and forty dark lamp posts.', color: 'white' }]
  ]
  if (ruinPos) {
    lines.push([
      { text: 'The lit path at your feet runs ' + (where || 'north') + ' to it. Follow the lanterns to the gate — the farm is at ', color: 'white' },
      { text: ruinPos[0] + ' ' + ruinPos[1] + ' ' + ruinPos[2], color: 'gold' },
      { text: '.', color: 'white' }
    ])
  }
  lines.push([{ text: 'Forty lamps. Fifteen people. One winter that nobody leaves.', color: 'gold', bold: true }])
  lines.push([{ text: 'Open your Quest Book. There is exactly one thing to do.', color: 'white' }])
  lines.forEach((l, i) => {
    valleyDelay(20 + i * 20, s => s.runCommandSilent('tellraw ' + name + ' ' + JSON.stringify(l)))
  })

  // The world border and the two counters start where §12.5 says they do.
  if (global.valley.once('world_opened')) {
    server.runCommandSilent('worldborder set 1500')
    server.runCommandSilent('bossbar set valley:folk value 0')
    server.runCommandSilent('bossbar set valley:lamps value 0')
  }
  console.info('[valley] first join handled for ' + name)
}

// =============================================================================
// 6. Handheld helpers the quests hand out.
//    §8 worked example 2: nobody waits on a chicken; the animals arrive in
//    crates and the feed makes a hen lay on use.
// =============================================================================
const CRATE_SPAWN = {
  'valley:hen_crate':   'minecraft:chicken',
  'valley:cow_crate':   'minecraft:cow',
  'valley:sheep_crate': 'minecraft:sheep'
}

// Q10 (three Hen Crates) and Q25 (Cow Crate + Sheep Crate).
Object.keys(CRATE_SPAWN).forEach(crateId => {
  ItemEvents.rightClicked(crateId, event => {
    let player = event.player
    if (player.level.isClientSide()) return
    let entityId = CRATE_SPAWN[crateId]
    let e = player.level.createEntity(entityId)
    if (!e) return
    e.setPosition(player.x, player.y, player.z)
    e.spawn()
    if (!player.isCreative()) event.item.count = event.item.count - 1
    global.valley.say(player, 'Marnie', 'There you are. Mind the gate.')
  })
})

// Chicken feed: the nearest hen within 8 blocks lays immediately.
ItemEvents.rightClicked('valley:chicken_feed', event => {
  let player = event.player
  if (player.level.isClientSide()) return
  let box = new $AABB(player.x - 8, player.y - 4, player.z - 8, player.x + 8, player.y + 4, player.z + 8)
  let laid = 0
  player.level.getEntitiesWithin(box).forEach(e => {
    if (laid > 0) return
    if (String(e.type) !== 'minecraft:chicken') return
    let b = player.level.getBlock(Math.floor(e.x), Math.floor(e.y), Math.floor(e.z))
    b.popItem(Item.of('minecraft:egg'))
    laid++
  })
  if (laid > 0 && !player.isCreative()) event.item.count = event.item.count - 1
  if (laid === 0) global.valley.say(player, 'Marnie', 'No hen close enough. Stand in the pen.')
})

// Q26: the Dredge Net. Q22 pays the net and Q26's text promises "each pull
// brings up 16 Lake Sand" over eight pulls — but the item had no handler, so
// valley:lake_sand had NO source anywhere in the pack and Q26 (and the whole
// silica -> Thermal Machine Frame line behind it) was unwinnable. This is that
// handler: use it in Nella's boat, or anywhere with open water within reach.
const dredgeLast = {}

function dredgePull(player) {
  if (!player || player.level.isClientSide()) return

  // Open water anywhere in a small box around the player: covers sitting in the
  // boat (water below), standing on the pier lip, and wading from the shallows.
  let px = Math.floor(player.x)
  let py = Math.floor(player.y)
  let pz = Math.floor(player.z)
  let wet = false
  for (let dy = 1; dy >= -4 && !wet; dy--) {
    for (let dx = -2; dx <= 2 && !wet; dx++) {
      for (let dz = -2; dz <= 2 && !wet; dz++) {
        let b = player.level.getBlock(px + dx, py + dy, pz + dz)
        if (String(b.id) === 'minecraft:water') wet = true
      }
    }
  }
  if (!wet) {
    global.valley.say(player, 'Nella', 'Not on dry land. Get in the boat, out over the shallows.')
    return
  }

  // One pull a second: it also swallows the off-hand double-fire, so eight
  // pulls is eight pulls and not eight clicks.
  let now = Date.now()
  let name = global.valley.pname(player)
  if (now - (dredgeLast[name] || 0) < 1000) return
  dredgeLast[name] = now

  player.give(Item.of('valley:lake_sand', 16))

  let pulls = parseInt(global.valley.get('valley_dredge_pulls', '0'), 10) + 1
  global.valley.set('valley_dredge_pulls', pulls)
  if (pulls === 1) {
    global.valley.say(player, 'Nella', 'Sixteen. Hold the rope, don\'t help.')
  } else if (pulls === 8) {
    global.valley.say(player, 'Nella', "That's the eight - a hundred and twenty-eight. Bram's waiting.")
  }
}

// Right-clicking at open water fires RightClickItem...
ItemEvents.rightClicked('valley:dredge_net', event => { dredgePull(event.player) })

// ...but a player standing in the shallows is usually looking AT the lake bed,
// and a block under the cursor sends the interaction to RightClickBlock instead,
// where the item event never fires. Both paths pull the same net. Guarded so an
// API surprise here can never take the rest of the spine down with it.
try {
  BlockEvents.rightClicked(event => {
    if (String(event.item.id) !== 'valley:dredge_net') return
    dredgePull(event.player)
  })
} catch (err) {
  console.warn('[valley] dredge net: block-click path unavailable (' + err + ')')
}

console.info('[valley] valley_core.js ok')
