// GENERATED by tools/scripts/make_npc_presets.py from story/npcs.json.
// Do not hand-edit: edit story/npcs.json and re-run the generator.
//
// Read by global.valley.greet() in valley_core.js, which /valley greet
// (valley_finales.js command tree) calls when a resident is right-clicked.
// Element 0 of each pool is the headline line that resident has always had.
global.valleyGreetings = {
  "marnie": {
    name: "Marnie",
    before: [
      "There you are. Kettle is on and I baked too much bread again.",
      "Sit down. You've got that look people get when they've been carrying something heavy up a hill.",
      "I put a loaf by for you. Don't tell Pip, he counts them.",
      "The Hearth's been lit in this room for thirty years. Some of those years it was the only thing that was.",
      "Eat something. I'm not asking."
    ],
    after: [
      "Full room tonight. Sit down before I give your chair away.",
      "I called it my inn this morning. Out loud, to Oda. I did not correct myself.",
      "I put a loaf by for you. Same as you put one by for me in February, only mine is better.",
      "The Hearth is lit, the oven is lit and the rooms upstairs are lit. Three fires. I keep counting them.",
      "Eat something. I cooked for fifteen tonight and there is still too much, which is the right amount."
    ]
  },
  "bram": {
    name: "Bram",
    before: [
      "Do not just stand there. Hold this, and do not let it slip.",
      "Mm. You're back. Don't touch the shaft, it's set.",
      "If a thing judders, look at the shaft. It's always the shaft.",
      "My father cut that stock. Label's still on the crate. That's all I'll say about it."
    ],
    after: [
      "Wheel is turning. Sixty years I waited. Come and look at it.",
      "Sixty-four years and that wheel's turned for two of them. Both since you came."
    ]
  },
  "oda": {
    name: "Oda",
    before: [
      "Shelves are thin and my ledger is thinner. What do you need.",
      "Ledger's open. It always is. That's rather the trouble with a ledger.",
      "I've counted the lamps again. I know. You don't have to say it.",
      "Buy something or don't, but stand out of the doorway."
    ],
    after: [
      "Books balance. Eleven years. Here, take the ledger. I mean it.",
      "Eleven years I kept the book of an empty shop. Now it's the book of a shop."
    ]
  },
  "nella": {
    name: "Nella",
    before: [
      "Lake is in a mood. So am I. Bring a rod anyway.",
      "Fish aren't biting. Sit down anyway.",
      "Boat's still beached. I know what you're going to say. Don't.",
      "Quiet down here. That's not a complaint.",
      "Good spot's past the reeds. Don't tell everyone."
    ],
    after: [
      "Turns out I like growing things. Do not make it strange.",
      "Fish aren't biting. Doesn't matter — the tomatoes are.",
      "Boat's mended. Took one afternoon. I had been calling it a week's work since before you came.",
      "Good spot's past the reeds. Tell people. I have decided I don't mind a crowd."
    ]
  },
  "halden": {
    name: "Halden",
    before: [
      "Sit a while. Tea first, then whatever it is you came to ask.",
      "Kettle's on. Everything else can wait ten minutes; it always could.",
      "The hedge doesn't need me. That's rather why I like it.",
      "Josie planted the first row of that. I only ever kept it trimmed.",
      "Green tea, or the strong one? The strong one is a decision."
    ],
    after: [
      "The cellar door is open and I am not carrying it alone now.",
      "Kettle's on. The book is open on the table and there are two chairs at it now.",
      "I read her shorthand out loud. Four years I let people think it was the hedge keeping me here.",
      "Josie planted the first row. I have planted the second, which took me rather longer than it should have.",
      "Green tea, or the strong one? Nobody has been ill since November, so have the strong one."
    ]
  },
  "tobin": {
    name: "Tobin",
    before: [
      "You own a pickaxe. Good. Look at this rock. No, really look.",
      "This one has quartz all through it. Nobody in this valley cares about quartz. I care enormously.",
      "I've marked it twice. The second set's in pink. Ignore the pink.",
      "I haven't slept, but that's not new information."
    ],
    after: [
      "Bram said good work. Out loud. I have not stopped hearing it.",
      "Look at this rock. It is the same rock. I keep it in my pocket now, which Bram says is normal.",
      "The pink marks were right. Nobody has said so out loud, and I am being very calm about it.",
      "Nobody believed me about the seam and now there's a mine, so.",
      "I haven't slept. The rig comes up the road when the road dries, and the road is drying."
    ]
  },
  "wisp": {
    name: "Wisp",
    before: [
      "You are come! I bring basket. Eat the purple one first, yes.",
      "You walk far today? Sit. I keep the good toadstools.",
      "Marsh is quiet, town is loud. Both is good. Different good.",
      "My people ask about you. I say: is the one who came and asked.",
      "I found a red one. I did not eat it. I am learning to not eat first."
    ],
    after: [
      "Two villages, one place now. My people sleep warm at the inn.",
      "You walk far today? Sit. I keep the good toadstools in the inn now, in a cupboard with a door.",
      "Marsh is quiet, town is loud. I sleep in the loud one now. Is strange. I like.",
      "My people do not ask about you now. They ask you. Is better, I think.",
      "Purple one grows in the warm glass house in winter now. I did not know it could do that."
    ]
  },
  "pip": {
    name: "Pip",
    before: [
      "The duck is called Biscuit. I decided it in about one second and I am not changing it.",
      "The duck went in the water bucket. On purpose, I think. It's fine.",
      "I'm allowed in the mill now if I don't touch anything. I touch nothing.",
      "Aunt Marnie says I ask too many questions. How many is too many?",
      "My satchel has a real buckle. Not a pretend one. A real one."
    ],
    after: [
      "I have a real job now. The duck supervises. Mostly badly.",
      "Biscuit went in the water trough in front of everybody at supper. She meant to. I saw her decide.",
      "I'm allowed to touch things in the mill now. Bram showed me which ones. I remember all of them.",
      "Aunt Marnie says I still ask too many questions. I asked her how many. She is thinking about it.",
      "I'm the one who rings the bell. Nobody else rings it. That was the deal and everybody heard it."
    ]
  },
  "ribbit_reed": {
    name: "Reed",
    before: [
      "Wisp says you are the new one. You are less tall than said.",
      "You are taller today. No. Same. I was wrong.",
      "Warm floor here. I sit on it. This is my job now."
    ]
  },
  "ribbit_sedge": {
    name: "Sedge",
    before: [
      "I carry too much. Is fine. Is what I am for, mostly.",
      "I carried the whole house. Wisp says I carried one box. We remember it different.",
      "If it is heavy, I am the one. That is the arrangement."
    ]
  },
  "ribbit_mudlark": {
    name: "Mudlark",
    before: [
      "The mud here is good mud. You should be proud of this.",
      "I brought you mud. Good mud. You do not have to keep it.",
      "The lamps make the puddles orange. I look at them a lot."
    ]
  },
  "ribbit_puddle": {
    name: "Puddle",
    before: [
      "Floor is warm and soup is hot. We stay now, I think. Yes. We stay.",
      "Soup again tonight. I checked. I check every night.",
      "We stay. I say it out loud so it stays true."
    ]
  },
  "newcomer_tess": {
    name: "Tess",
    before: [
      "Saw your noticeboard from the ridge road. Is there a room?",
      "Room's warm. I keep waking up surprised about it.",
      "I'll pay the week, and then probably the year."
    ]
  },
  "newcomer_corin": {
    name: "Corin",
    before: [
      "I mend roofs. Heard this valley has roofs again. Here I am.",
      "Third roof this week. Good roofs. Somebody built them right the first time.",
      "Whoever laid that mill thatch knew what they were doing. Was it you?"
    ]
  },
  "newcomer_mab": {
    name: "Mab",
    before: [
      "I left here in the bad winter. I am not leaving twice.",
      "I know this lane. I know which post leans.",
      "I walked out of here in February eleven years ago. I came back in daylight, which is different."
    ]
  }
}
