// =============================================================================
// valley_core.js — Little Kettle Valley: the spine.
//
// Owns:
//   * global.valley           the helper API every other valley script uses
//   * server.persistentData   anchor, home, lamps[], world stages, finale flags
//   * the FTB Teams auto-party (§9-A "the couple's team")
//   * the first-join handler (§2 premise, §12.5 first-join command block)
//   * the animal-crate / chicken-feed right-click handlers (§8 worked ex. 2)
//
// Engine notes verified against kubejs-forge-2001.6.5-build.26.jar:
//   * PlayerEvents has NO wakeUp/sleep event in this build. Sleep detection
//     lives in valley_checks.js as a slow-tick poll.
//   * There is no player.username. Use player.profile.name.
//   * server.persistentData is a CompoundTag (MinecraftServerMixin implements
//     WithPersistentData). Everything below stores FLAT primitive keys, because
//     nested CompoundTags returned by getCompound() are not reliably attached.
//   * There is no exposed scheduler binding, so delays are a tick queue here.
//
// THE WORLD IS SHIPPED (docs/transitions-design.md architecture A). There is no anchoring
// left to do: the farm, the town, the road, the forty posts, the sealed Works and the
// cellar are all standing before the first login, and every coordinate the pack needs is a
// constant in pack/kubejs/data/valley/valley_sites.json, loaded as global.valleySites by
// the generated valley_sites.js. Nothing in this file places, cuts, levels or searches for
// anything any more; the ruin finder, its lit path, its pad and the spawn signpost are all
// gone, because all four of those things are in the world already.
// =============================================================================

// -----------------------------------------------------------------------------
// 0. Tunables. Every anchor-relative offset in the pack lives here so the
//    checks and the finales can never disagree. [dx, dy, dz] from the Town
//    Anchor unless the name says HOME_.
// -----------------------------------------------------------------------------
// -----------------------------------------------------------------------------
// THE REGISTRY. Every coordinate in the pack, as a constant.
//
// valley_sites.js is GENERATED from valley_sites.json by tools/scripts/plan_town.py and
// carries `// priority: 2000`, so KubeJS loads it before town_plan.js (1000) and before
// every valley_*.js. That ordering is load-bearing and it is the second time it has
// mattered: the shipped log has valley_core.js at 00:15:02.929 and town_plan.js at
// 00:15:02.953, i.e. the plan loaded SECOND, and every mark in the pack was quietly coming
// out of a hand-typed fallback rather than the plan. See docs/mod-decisions.md.
// -----------------------------------------------------------------------------
const SITES = (typeof global.valleySites !== 'undefined') ? global.valleySites : null
if (!SITES) {
  console.error('[valley] valley_sites.js did NOT load. Every coordinate in the pack lives ' +
                'in it; run tools/scripts/plan_town.py --site and re-sync the server.')
}

// A registry read that says which key was missing rather than returning undefined into
// arithmetic three files away.
function siteAt(path) {
  if (!SITES) return null
  let node = SITES
  let parts = String(path).split('.')
  for (let i = 0; i < parts.length; i++) {
    if (node === null || node === undefined) break
    node = node[parts[i]]
  }
  if (node === null || node === undefined) {
    console.warn('[valley] no "' + path + '" in valley_sites.json')
    return null
  }
  return node
}

// The forty posts, in LIGHTING ORDER, split by the quest that lights each one. A registry
// entry's `pos` is the FENCE; the cage lamp sits one block above it, and the lamp is what a
// setblock lights, so that is what these lists carry.
function lampHeads(route) {
  let out = []
  let list = (SITES && SITES.lamps) ? SITES.lamps : []
  for (let i = 0; i < list.length; i++) {
    if (route && list[i].route !== route) continue
    out.push([list[i].pos[0], list[i].pos[1] + 1, list[i].pos[2]])
  }
  return out
}

const VALLEY = {
  // --- Named marks. ABSOLUTE, out of the registry. -------------------------
  // These used to be anchor-relative offsets read out of the town plan, because the anchor
  // was wherever the player drove a stake. The anchor is a constant now and so are the
  // marks: `square`, `board`, `inn`, `mill`, `granary`, `lake`, `works`, `greenhouse`,
  // `bathhouse`, `echo_cave`.
  MARKS: (SITES && SITES.marks) ? SITES.marks : {},

  // --- Named marks, anchor-relative (LEGACY) -------------------------------
  // These come from the TOWN PLAN (town_plan.js, generated by
  // tools/scripts/plan_town.py from the installed structure NBTs), because the
  // mark and the building have to move together: `inn` is the tavern piece's
  // own campfire, `mill` is the yard block in front of the windmill's door,
  // `granary`/`greenhouse`/`bathhouse` are the corners the plan solved for.
  // KubeJS loads server_scripts alphabetically, so town_plan.js ("t") is
  // already loaded when this file ("v") runs. The literals below are the
  // fallback for a pack whose plan file has been removed, and are the only
  // marks nothing in the plan can move: the square, the board, the lake, the
  // Works and the echo cave.
  OFF: (typeof global.valleyTownPlan !== 'undefined' && global.valleyTownPlan.OFF)
    ? global.valleyTownPlan.OFF
    : {
        square:      [0, 1, 0],
        board:       [0, 1, -5],
        inn:         [23, 1, 2],
        mill:        [-27, 0, 5],
        granary:     [-36, 1, 18],
        lake:        [0, 1, 34],
        works:       [34, -6, -20],
        greenhouse:  [-24, 1, -13],
        bathhouse:   [29, 1, 16],
        echo_cave:   [34, -30, -20]
      },

  // --- Box sizes for "is the player standing in X" checks, in blocks -------
  BOX: {
    works:     [10, 6, 10],
    echo_cave: [8, 6, 8],
    cellar:    [7, 4, 7]
  },

  // Q5 and Q55 both mean "in Josie's cellar". That room is a real room in the shipped
  // world now — a stone-brick chamber at the bottom of forty blocks of gravel — so both
  // are the same box test against the registry's own cellar shell, and neither is a
  // guess at a depth any more.
  CELLAR_BOX: (SITES && SITES.cellar) ? SITES.cellar.box : null,
  CELLAR_STAND: (SITES && SITES.cellar) ? SITES.cellar.stand : null,

  // Q90: the bare fortieth post on Josie's porch, and the cell its lamp goes in.
  PORCH: (SITES && SITES.cottage) ? SITES.cottage.porch : null,

  // --- THE LAMP BLOCK. ----------------------------------------------------- candlelight:lamp was wrong twice over: its blockstate
  // (letsdo-candlelight-forge-1.2.13.jar, assets/candlelight/blockstates/
  // lamp.json) carries ONLY `hanging`, so it has no lit form at all and the
  // Act IV lever could never turn it on; and its model is a 6x6 base, a 2x2
  // post and a cloth shade — a bedside table lamp sitting on the ground, not
  // a lamp post. createdeco:yellow_copper_lamp is a cage lamp with a real
  // lit=false|true, and copper is the valley's own metal.
  //
  // CageLampBlock#shouldBeLit is `inverted XOR redstone into the mounting
  // face`, and CageLampBlock#neighborChanged writes that answer straight back
  // over whatever `lit` a setblock wrote. So `lit` on its own does not hold:
  // a lamp that must STAY lit with no redstone on it is inverted=true,lit=true
  // and a dark one is inverted=false,lit=false. facing=up mounts it on the
  // block below, which is the fence post.
  //
  // A post is TWO blocks: LAMP_POST at the offset's own y, and the lamp at
  // y + LAMP_HEAD. Everything stored in persistentData.lamps[] is the LAMP's
  // position, never the post's, because that is what the Act IV sweep sets.
  // valley_finales.js mirrors these three strings as file-local constants
  // (they are baked into command arrays at script load) — change both.
  LAMP_BLOCK: 'createdeco:yellow_copper_lamp',
  LAMP_POST:  'minecraft:oak_fence',
  LAMP_HEAD:  1,
  LAMP_DARK:  'createdeco:yellow_copper_lamp[facing=up,inverted=false,lit=false]',
  LAMP_LIT:   'createdeco:yellow_copper_lamp[facing=up,inverted=true,lit=true]',
  LAMP_TOLERANCE: 2,

  // --- The Lantern Road, out of the registry -------------------------------
  // Forty posts stand in the world from the first second and every one of them is dark.
  // Thirty-nine carry a cage lamp; the fortieth, on Josie's own porch, is a bare fence and
  // Q90 is the only thing that ever puts a light on it. Nothing in the pack places a post
  // any more — the story lights what is already there, in this order.
  //
  //   LAMPS_ALL     all forty lamp CELLS (post + [0,1,0]), in lighting order
  //   LAMPS_FINALE  the four on the plaza kerb  (Act I)
  //   LAMPS_Q07     the two at the head of the High Street (the stake)
  //   LAMPS_Q34     the four, mill to square  (Act II)
  //   LAMPS_Q74     the rest, square to lake to farm  (Act IV)
  //   LAMPS_Q90     Josie's porch. One entry, and it ships bare.
  LAMPS_ALL:    lampHeads(null),
  LAMPS_FINALE: lampHeads('finale'),
  LAMPS_Q07:    lampHeads('q07'),
  LAMPS_Q34:    lampHeads('q34'),
  LAMPS_Q74:    lampHeads('q74'),
  LAMPS_Q90:    lampHeads('q90'),

  // --- Resident chat colours (§writer-brief rule 10) -----------------------
  // The quest book is the authority here: five of these nine used to disagree
  // with the tellraw colours in story/quests/*.json, so the same resident spoke
  // in a different colour depending on whether the line came from v.sayAll or
  // from a quest reward — and in a finale Marnie and Tobin came out identical.
  // Josie and Bram are both gray on purpose: Josie is chalk and paper and
  // almost never speaks aloud, and Bram's gray is established five times in the
  // book.
  VOICE: {
    Josie:  'gray',
    Marnie: 'light_purple',
    Bram:   'gray',
    Oda:    'gold',
    Nella:  'aqua',
    Halden: 'green',
    Tobin:  'yellow',
    Wisp:   'dark_green',
    Pip:    'red'
  },

  // --- The eight chain-closing quests, for Standing: Trusted (§5) ----------
  STANDING_CHAINS: ['q59', 'q60', 'q62', 'q63', 'q73', 'q75', 'q77', 'q85'],

  // --- Custom item ids used by the runtime handlers ------------------------
  ITEM: {
    letter: 'valley:letter',
    deed:   'valley:deed',
    kettle: 'herbalbrews:copper_tea_kettle'   // the Copper Kettle over the hearth
  }
}

const $AABB = Java.loadClass('net.minecraft.world.phys.AABB')

// -----------------------------------------------------------------------------
// 1. persistentData. Flat keys only — see the header note.
// -----------------------------------------------------------------------------
function pdata() {
  let s = global.valleyServer
  return s ? s.persistentData : null
}

function pdGet(key, fallback) {
  let d = pdata()
  if (!d || !d.contains(key)) return fallback
  return d.getString(key)
}

function pdPut(key, value) {
  let d = pdata()
  if (d) d.putString(key, String(value))
}

function pdFlag(key) {
  let d = pdata()
  return !!(d && d.contains(key))
}

function pdSetFlag(key) {
  let d = pdata()
  if (d) d.putString(key, '1')
}

function posToStr(p) { return p[0] + ',' + p[1] + ',' + p[2] }

function strToPos(s) {
  if (!s) return null
  let parts = String(s).split(',')
  if (parts.length !== 3) return null
  let x = parseInt(parts[0], 10), y = parseInt(parts[1], 10), z = parseInt(parts[2], 10)
  if (isNaN(x) || isNaN(y) || isNaN(z)) return null
  return [x, y, z]
}

// -----------------------------------------------------------------------------
// 2. The delay queue. Replaces `/schedule function`, which needs a datapack
//    function we do not ship. Drained by the tick handler at the bottom; the
//    array is empty except during a finale, so the cost is one length check.
// -----------------------------------------------------------------------------
const valleyPending = []

function valleyDelay(ticks, fn) {
  valleyPending.push({ at: global.valleyTick + ticks, fn: fn })
}

// -----------------------------------------------------------------------------
// 3. The public API. Everything in valley_gates / valley_checks /
//    valley_finales, and every act writer's KubeJS-facing assumption, goes
//    through this object.
// -----------------------------------------------------------------------------
global.valley = {

  C: VALLEY,

  // ---- server handle ------------------------------------------------------
  server: function () { return global.valleyServer },

  // ---- THE REGISTRY. -----------------------------------------------------
  // These three used to be persistentData: the anchor was wherever a stake landed, home
  // was wherever a waystone landed, and the ruin was wherever a first-join search found
  // room for a pad. All three are constants now — the world is shipped — so they read
  // straight out of valley_sites.json and nothing can move them.
  //
  // The one op override that survives is `/valley anchor set`, which writes
  // persistentData and is read first: it is how a broken world gets nudged, and it is
  // deliberately not reachable from a quest.
  site: function (path) { return siteAt(path) },

  anchor: function () {
    return strToPos(pdGet('valley_anchor', null)) || siteAt('anchor')
  },

  setAnchor: function (x, y, z) {
    pdPut('valley_anchor', posToStr([x, y, z]))
    console.info('[valley] Town Anchor OVERRIDDEN to ' + x + ' ' + y + ' ' + z +
                 ' (the registry says ' + String(siteAt('anchor')) + ')')
  },

  // ---- Home. --------------------------------------------------------------
  // The hearthstone until the Homestead Waystone is standing on it, and the waystone cell
  // after — which is exactly the block the player puts down in Q2 and exactly one block
  // up. Everything Home-relative in the pack (the cellar, the pen, the porch) is measured
  // from the registry, so the one-block difference is cosmetic; what it buys is that
  // `v.home()` is never null, so no check in the pack can silently no-op before Q2.
  home: function () {
    return strToPos(pdGet('valley_home', null)) || siteAt('hearth')
  },

  homeSet: function () { return !!strToPos(pdGet('valley_home', null)) },

  setHome: function (x, y, z) {
    pdPut('valley_home', posToStr([x, y, z]))
    console.info('[valley] Home is on the hearthstone: ' + x + ' ' + y + ' ' + z)
  },

  // ---- The Kettle farm's hearthstone. -------------------------------------
  // It is a block in the shipped world, at the centre of a cottage that has been standing
  // there since before the player logged in. It is never placed and never moves.
  ruin: function () { return siteAt('hearth') },

  hearth: function () { return siteAt('hearth') },

  // ---- anchor + offset -> absolute [x,y,z]. --------------------------------
  offset: function (off) {
    let a = global.valley.anchor()
    if (!a) return null
    return [a[0] + off[0], a[1] + off[1], a[2] + off[2]]
  },

  // ---- Named mark by key, out of the registry -----------------------------
  mark: function (name) {
    let m = VALLEY.MARKS[name]
    if (m) return [m[0], m[1], m[2]]
    // Nothing should reach this. A mark the registry has never heard of is a typo, and
    // the anchor-relative fallback is only here so that one is a wrong place rather than
    // a thrown exception inside a finale.
    let off = VALLEY.OFF[name]
    if (!off) { console.warn('[valley] no mark "' + name + '"'); return null }
    console.warn('[valley] mark "' + name + '" is not in the registry; using the offset')
    return global.valley.offset(off)
  },

  // ---- Complete a quest for the player's TEAM (§P2). ---------------------
  // key is an outline key: 'q07'. Silently no-ops if the compiler has not
  // emitted that key into _quest_ids.js yet, so a half-built pack still runs.
  complete: function (player, key) {
    let ids = global.valleyQuestIds || {}
    let id = ids[key]
    if (!id) {
      if (!global.valleyMissingWarned) global.valleyMissingWarned = {}
      if (!global.valleyMissingWarned[key]) {
        global.valleyMissingWarned[key] = true
        console.warn('[valley] no quest id for "' + key + '" in _quest_ids.js — skipping completion')
      }
      return false
    }
    let s = global.valleyServer
    if (!s) return false
    s.runCommandSilent('ftbquests change_progress ' + global.valley.pname(player) +
                       ' complete ' + global.valley.cmdId(id))
    return true
  },

  // ---- A quest id in the form /ftbquests will actually parse. -------------
  // FTB Quests reads its object argument with QuestObjectBase.parseCodeString,
  // which is Long.parseLong(s, 16) — SIGNED. Any id whose top bit is set (a
  // first hex digit of 8-F) overflows, the NumberFormatException is swallowed,
  // and the argument comes back as 0, so the command answers "Invalid Object
  // ID" and completes nothing. 66 of this pack's 126 quest ids sit in that
  // half of the space, which silently disabled fourteen of the twenty-four
  // KubeJS auto-completions — q01, q02, q65 and q71 among them.
  //
  // compile_quests.py now clears bit 63 when it derives an id, so nothing the
  // compiler emits reaches this branch any more — but the same id also has to
  // survive being read back out of a file someone hand-edited, and a silent
  // no-op is the worst possible failure here. The same long written as a
  // NEGATIVE hex literal parses, and '-' is legal in an unquoted Brigadier
  // string, so that is the fallback. Arithmetic is nibble by nibble because a
  // 64-bit id does not survive a JS double.
  cmdId: function (hex) {
    let h = String(hex).toUpperCase()
    if (h.length < 16 || '89ABCDEF'.indexOf(h.charAt(0)) < 0) return h
    let d = []
    for (let i = 0; i < 16; i++) d.push(15 - parseInt(h.charAt(i), 16))
    let carry = 1
    for (let i = 15; i >= 0; i--) {
      let v = d[i] + carry
      d[i] = v & 15
      carry = v >> 4
    }
    let out = ''
    for (let i = 0; i < 16; i++) out += '0123456789ABCDEF'.charAt(d[i])
    out = out.replace(/^0+/, '')
    return '-' + (out === '' ? '0' : out)
  },

  // ---- The player's login name. There is no player.username in 2001.6.5. --
  pname: function (player) { return player.profile.name },

  // ---- Give a KubeJS stage to every ONLINE member of a team. -------------
  // Stages are per player (§naming contract), so a team-wide grant is a loop.
  // `team` may be an FTB team object, or null for "everyone online".
  stageAll: function (team, stage) {
    let s = global.valleyServer
    if (!s) return
    s.players.forEach(p => {
      if (team) {
        // p.team only exists when the FTB Teams integration is present; if the
        // lookup fails for any reason we fall back to "everyone online", which
        // is correct for a one-team world and harmless for two.
        try { if (p.team && String(p.team.id) !== String(team.id)) return } catch (err) { /* ignore */ }
      }
      if (!p.stages.has(stage)) p.stages.add(stage)
    })
  },

  // ---- One resident line, in that resident's colour (§writer-brief 10). ---
  // Built as tellraw JSON so nothing depends on a Component builder overload.
  say: function (player, who, text) {
    let colour = VALLEY.VOICE[who] || 'white'
    let json = [
      { text: who + ': ', color: colour, bold: false },
      { text: text, color: 'white', italic: true }
    ]
    let s = global.valleyServer
    if (!s) return
    s.runCommandSilent('tellraw ' + global.valley.pname(player) + ' ' + JSON.stringify(json))
  },

  // ---- A resident's greeting line, picked out of that resident's pool. ----
  //
  // Every resident used to have exactly two lines for the whole sixteen-hour
  // pack — one before their arc closed, one after — wired as a pair of
  // /info_message actions on the NPC. /info_message renders as a screen title,
  // which is why the generator refuses a Cmd over 120 characters or containing
  // a double quote; that ceiling is what kept the town to two sentences each.
  //
  // So the NPC now runs `/valley greet <key> <before|after> @initiator` and the
  // lines live in valley_greetings.js (GENERATED from story/npcs.json). The
  // scoreboard condition that chooses before/after is unchanged and still lives
  // on the Easy NPC action, so the arc gating is the same verified mechanism.
  //
  // Rotation is by world day plus a hash of the player's name: stable within a
  // day (clicking Marnie twice in a row does not shuffle), different from one
  // day to the next, and different between two players standing side by side.
  greet: function (playerName, key, phase) {
    let pools = global.valleyGreetings
    if (!pools) return
    let entry = pools[key]
    if (!entry) { console.warn('[valley] /valley greet: unknown resident ' + key); return }
    let pool = (phase === 'after' && entry.after) ? entry.after : entry.before
    if (!pool || !pool.length) return

    let s = global.valleyServer
    if (!s) return
    let player = null
    try { player = s.getPlayer(playerName) } catch (err) { player = null }
    if (!player) return

    let day = 0
    try { day = Math.floor(s.overworld().getDayTime() / 24000) } catch (err) { day = 0 }
    let h = 0
    let n = String(playerName)
    for (let i = 0; i < n.length; i++) h = (h * 31 + n.charCodeAt(i)) % 100003
    let idx = (day + h) % pool.length
    if (idx < 0) idx += pool.length

    global.valley.say(player, entry.name, pool[idx])
  },

  // ---- Same line, to everyone. Used by the finales. ----------------------
  sayAll: function (who, text) {
    let colour = VALLEY.VOICE[who] || 'white'
    let json = [
      { text: who + ': ', color: colour },
      { text: text, color: 'white', italic: true }
    ]
    let s = global.valleyServer
    if (s) s.runCommandSilent('tellraw @a ' + JSON.stringify(json))
  },

  // ---- World stages. There is no GameStages mod; a world stage is a flag in
  //      persistentData (§9-F "world stages vs team stages"). -------------
  hasWorldStage: function (id) { return pdFlag('valley_ws_' + id) },
  addWorldStage: function (id) {
    if (!pdFlag('valley_ws_' + id)) {
      pdSetFlag('valley_ws_' + id)
      console.info('[valley] world stage granted: ' + id)
    }
  },

  // ---- The Lantern Road. -------------------------------------------------
  // Forty cells, in lighting order, straight out of the registry. This used to be a CSV
  // in persistentData that the block-placement listener appended to, because the posts did
  // not exist until the player built them; they exist now, so the list is a constant and
  // the only state left is how many have been LIT.
  lamps: function () { return VALLEY.LAMPS_ALL.slice(0) },

  lampsOnRoute: function (route) {
    let key = 'LAMPS_' + String(route).toUpperCase()
    return (VALLEY[key] || []).slice(0)
  },

  // How many of the forty are burning. Kept in persistentData because it drives the
  // bossbar and because a route can be lit by a quest, by a finale or by an op.
  lampsLit: function () { return parseInt(pdGet('valley_lamps_lit', '0'), 10) || 0 },

  setLampsLit: function (n) {
    let v = Math.max(0, Math.min(40, n | 0))
    pdPut('valley_lamps_lit', v)
    let s = global.valleyServer
    if (s) s.runCommandSilent('bossbar set valley:lamps value ' + v)
    return v
  },

  // Light a list of lamp cells, one per tick, and count them. `sound` false for the
  // silent backstop pass. Returns how many cells it was handed.
  lightLamps: function (cells, sound) {
    let s = global.valleyServer
    if (!s || !cells || !cells.length) return 0
    cells.forEach((p, i) => {
      valleyDelay(i, srv => {
        srv.runCommandSilent('setblock ' + p[0] + ' ' + p[1] + ' ' + p[2] + ' ' + VALLEY.LAMP_LIT)
        if (sound === false) return
        srv.runCommandSilent('particle minecraft:end_rod ' + p[0] + ' ' + (p[1] + 1) + ' ' +
                             p[2] + ' 0.2 0.2 0.2 0.01 8 force @a')
        srv.runCommandSilent('playsound minecraft:block.copper.place master @a ' +
                             p[0] + ' ' + p[1] + ' ' + p[2] + ' 0.6 1.6')
      })
    })
    return cells.length
  },

  // ---- Finale idempotency (§P7). ----------------------------------------
  finaleDone: function (act) { return pdFlag('valley_finale_' + act) },
  markFinale: function (act) { pdSetFlag('valley_finale_' + act) },

  // ==========================================================================
  // Standing: Trusted (§5, §12.3) — Q86's second condition.
  //
  // Standing is "how many of the eight named resident chains this TEAM has
  // closed". The authoritative record is a ledger of flags in
  // server.persistentData, written by a silent command reward on each of the
  // eight closing quests:
  //     /valley standing <key> {team}
  // CommandReward#claim substitutes only @p, {x} {y} {z}, {team}, {quest} and
  // {chapter}. There is NO {long_team_id}; {team} is the FTB Teams SHORT TEAM
  // NAME, a plain string. The ledger is therefore keyed on that string, and
  // teamId() below resolves the same short name for a caller with no argument.
  //
  // standingApiClosed() below is a top-up, not the source of truth: it reads
  // the FTB XMod Compat KubeJS binding when that binding exists, so a chain
  // closed before this ledger shipped (or claimed while the reward failed)
  // still counts. It returns null the moment anything about the binding is
  // not what we expect, and the ledger carries on alone.
  // ==========================================================================

  STANDING_REQUIRED: 6,

  // The eight chain keys, in story order.
  standingChains: function () { return VALLEY.STANDING_CHAINS.slice(0) },

  // The FTB team SHORT NAME for this player, or their login name when FTB
  // Teams is not answering. This is what {team} expands to in a command
  // reward, so both halves of the ledger agree on one key.
  teamId: function (player) {
    try {
      let t = player ? player.team : null
      if (t) {
        let n = t.shortName
        if (!n) { try { n = t.getShortName() } catch (e2) { n = null } }
        if (!n) n = t.name
        if (n) return String(n)
      }
    } catch (err) { /* no FTB Teams integration; fall through */ }
    return player ? global.valley.pname(player) : 'server'
  },

  // The FTB Teams short name for this player, or NULL when FTB Teams is not
  // answering. teamId() above falls back to the LOGIN NAME on purpose, which
  // is right for a ledger key and wrong for anything that has to be handed
  // back to `ftbteams party join` — hence this second, strict reader.
  teamShortName: function (player) {
    try {
      let t = player ? player.team : null
      if (!t) return null
      let n = t.shortName
      if (!n) { try { n = t.getShortName() } catch (e2) { n = null } }
      if (!n) n = t.name
      return n ? String(n) : null
    } catch (err) { return null }
  },

  // persistentData is flat primitives only (see the header note), so the team
  // and the quest key are folded into the key name.
  standingSlot: function (teamId, questKey) {
    return 'valley_standing_' + String(teamId).replace(/[^A-Za-z0-9]/g, '') + '_' + questKey
  },

  // Returns true the first time this chain is recorded for this team.
  recordStanding: function (teamId, questKey) {
    if (VALLEY.STANDING_CHAINS.indexOf(questKey) === -1) return false
    let slot = global.valley.standingSlot(teamId, questKey)
    if (pdFlag(slot)) return false
    pdSetFlag(slot)
    console.info('[valley] standing: ' + questKey + ' recorded for team ' + teamId)
    return true
  },

  standingClosed: function (teamId) {
    return VALLEY.STANDING_CHAINS.filter(k => pdFlag(global.valley.standingSlot(teamId, k)))
  },

  standingCount: function (teamId) { return global.valley.standingClosed(teamId).length },

  standingGranted: function (teamId) {
    return pdFlag('valley_standing_done_' + String(teamId).replace(/[^A-Za-z0-9]/g, ''))
  },

  markStandingGranted: function (teamId) {
    pdSetFlag('valley_standing_done_' + String(teamId).replace(/[^A-Za-z0-9]/g, ''))
  },

  // Which of the eight FTB Quests itself says are complete for this player's
  // team, or null when the binding is absent or shaped differently.
  //
  // Binding verified in ftb-xmod-compat-forge-2.1.3.jar:
  //   KubeJSIntegration#registerBindings  -> add("FTBQuests", FTBQuestsKubeJSWrapper.INSTANCE)
  //   FTBQuestsKubeJSWrapper#getServerDataFromPlayer(Player)
  //                                       -> FTBQuestsKubeJSPlayerData
  //   FTBQuestsKubeJSTeamData#isCompleted(Object) -> boolean
  //     (resolves the argument through BaseQuestFile#getID, which parses the
  //      16-char hex ids _quest_ids.js already stores)
  standingApiClosed: function (player) {
    if (typeof FTBQuests === 'undefined' || !player) return null
    let ids = global.valleyQuestIds || {}
    let out = []
    try {
      let data = FTBQuests.getServerDataFromPlayer(player)
      if (!data) return null
      for (let i = 0; i < VALLEY.STANDING_CHAINS.length; i++) {
        let k = VALLEY.STANDING_CHAINS[i]
        let id = ids[k]
        if (!id) continue
        if (data.isCompleted(id)) out.push(k)
      }
    } catch (err) {
      if (!global.valleyStandingApiWarned) {
        global.valleyStandingApiWarned = true
        console.warn('[valley] FTBQuests binding unusable for Standing (' + err + '); ' +
                     'the command-reward ledger is authoritative and unaffected.')
      }
      return null
    }
    return out
  },

  // ---- Generic once-per-TEAM latch, used by the checks. ------------------
  // A checkmark quest is completed per FTB Teams PARTY, so the latch that
  // stops it re-firing has to be per party too. A flat world-level latch
  // (which is what this was) let the first party through and then hard-stuck
  // the second one on every KubeJS-completed quest — twenty of them, starting
  // at Q2. The slot name folds in the same sanitised short name the Standing
  // ledger uses, because persistentData is flat primitives only.
  //
  // `team` omitted means world-level, which is exactly what the genuinely
  // one-per-world flags want (world_opened, ruin_placed).
  onceSlot: function (key, team) {
    let t = team ? String(team).replace(/[^A-Za-z0-9]/g, '') : 'w'
    return 'valley_once_' + t + '_' + key
  },
  once: function (key, team) {
    let k = global.valley.onceSlot(key, team)
    if (pdFlag(k)) return false
    pdSetFlag(k)
    return true
  },
  isDone: function (key, team) { return pdFlag(global.valley.onceSlot(key, team)) },

  // ---- Delay, in ticks. ---------------------------------------------------
  delay: valleyDelay,

  // ---- Raw persistent storage, for the checks' per-player baselines. ------
  get: function (key, fallback) { return pdGet(key, fallback) },
  set: function (key, value) { pdPut(key, value) },

  // ---- Entities of a type inside a box centred on [x,y,z]. ---------------
  countNear: function (level, pos, radius, typePrefix) {
    let box = new $AABB(
      pos[0] - radius, pos[1] - radius, pos[2] - radius,
      pos[0] + radius, pos[1] + radius, pos[2] + radius
    )
    let n = 0
    level.getEntitiesWithin(box).forEach(e => {
      if (String(e.type).indexOf(typePrefix) === 0) n++
    })
    return n
  },

  // ---- Is this player inside the box [centre, size]? ---------------------
  inBox: function (player, centre, size) {
    if (!centre) return false
    return Math.abs(player.x - centre[0]) <= size[0] &&
           Math.abs(player.y - centre[1]) <= size[1] &&
           Math.abs(player.z - centre[2]) <= size[2]
  },

  // ---- Horizontal distance, for "within N of Home" checks. ---------------
  flatDist: function (player, pos) {
    let dx = player.x - pos[0], dz = player.z - pos[2]
    return Math.sqrt(dx * dx + dz * dz)
  }
}

// =============================================================================
// 4. Server lifecycle
// =============================================================================
global.valleyTick = 0

ServerEvents.loaded(event => {
  global.valleyServer = event.server
  global.valleyTick = 0
  valleyPending.length = 0

  // §P6 — the two counters are bossbars. Re-issued on every load; `add` on an
  // existing bar is a harmless failure.
  let s = event.server
  s.runCommandSilent('bossbar add valley:lamps {"text":"Lantern Road","color":"gold"}')
  s.runCommandSilent('bossbar set valley:lamps max 40')
  s.runCommandSilent('bossbar set valley:lamps players @a')
  s.runCommandSilent('bossbar add valley:folk {"text":"Residents","color":"green"}')
  s.runCommandSilent('bossbar set valley:folk max 15')
  s.runCommandSilent('bossbar set valley:folk players @a')

  let a = global.valley.anchor()
  console.info('[valley] core loaded. Anchor: ' + (a ? a.join(' ') : 'not set yet'))
})

ServerEvents.unloaded(event => {
  global.valleyServer = null
  valleyPending.length = 0
})

// The one shared tick handler for the delay queue. valley_checks.js keeps its
// own slow-tick poll; this one only drains scheduled finale steps.
ServerEvents.tick(event => {
  global.valleyTick++
  if (valleyPending.length === 0) return
  for (let i = valleyPending.length - 1; i >= 0; i--) {
    if (valleyPending[i].at <= global.valleyTick) {
      let job = valleyPending.splice(i, 1)[0]
      try { job.fn(event.server) } catch (err) { console.error('[valley] delayed step failed: ' + err) }
    }
  }
})

// =============================================================================
// 5. Login: the FTB Teams auto-party, then the first-join handler.
// =============================================================================
PlayerEvents.loggedIn(event => {
  let player = event.entity
  let server = global.valleyServer || player.server
  if (!server) return
  let name = global.valley.pname(player)

  // ---- §9-A: everybody lands on ONE party. Guarded by the per-player stage
  // cozy_party; skipped entirely for anyone holding solo_team (§9-B, the
  // second letter / a player who wants their own book).
  //
  // `ftbteams party join Cozy` can never work: the join argument is a party
  // ID or short name, not the display name, and every player who ran the old
  // pair of commands ended up on their OWN party that was also displayed as
  // "Cozy". Both commands are runCommandSilent, so nothing said so — and FTB
  // Quests then keyed progress off a different team id per player.
  //
  // So: the FIRST player through creates the party and we write down the real
  // short name FTB Teams gave it. Everyone after that joins THAT string, and
  // only falls through to creating one if the join left them where they were.
  if (!player.stages.has('cozy_party') && !player.stages.has('solo_team')) {
    player.stages.add('cozy_party')
    valleyJoinParty(server, player, name)
  }

  startObjectiveLoop()

  // ---- §12.5 first-join block. Per player, once.
  if (!player.stages.has('first_join')) {
    player.stages.add('first_join')
    valleyFirstJoin(server, player, name)
  }

  // Re-attach the bossbars for this player.
  server.runCommandSilent('bossbar set valley:lamps players @a')
  server.runCommandSilent('bossbar set valley:folk players @a')

  // ---- A5: the one push notification in the pack, and it kills itself.
  // Create: Astral's whole nag budget is a single aqua line on login, gated by a
  // read_quest player stage that valley_checks.js sets the first time the Quest
  // Book is right-clicked. After that it never appears again, on this login or any
  // future one, and the hover tells her how to stop it before she has to wonder.
  // Delayed past the first-join chat so it lands last rather than in the middle.
  if (!player.stages.has('read_quest')) {
    valleyDelay(60, s => {
      if (player.stages.has('read_quest')) return
      s.runCommandSilent('tellraw ' + name + ' ' + JSON.stringify({
        text: 'Right-click the Quest Book in your bag, or press J.',
        color: 'aqua', underlined: true,
        hoverEvent: { action: 'show_text', contents:
          'The book is the list of what to do next. Open it once and this line stops for good.' }
      }))
    })
  }
})

// The party dance. Split out of loggedIn so the retry can run a tick later:
// FTB Teams applies a join/create on the command's own tick, so player.team is
// still the old value at the moment the command returns.
function valleyJoinParty(server, player, name) {
  let stored = pdGet('valley_team', null)

  if (stored) {
    server.runCommandSilent('execute as ' + name + ' run ftbteams party join ' + stored)
  }

  valleyDelay(1, s => {
    let now = global.valley.teamShortName(player)
    // Already on the pack's party — nothing more to do.
    if (stored && now && now === stored) {
      console.info('[valley] ' + name + ' joined party ' + stored)
      return
    }
    // No party recorded yet, or the join did not take: make one and record
    // whatever short name FTB Teams actually assigned it.
    s.runCommandSilent('execute as ' + name + ' run ftbteams party create Cozy')
    s.runCommandSilent('execute as ' + name + ' run ftbteams party settings free_to_join true')
    valleyDelay(1, s2 => {
      let made = global.valley.teamShortName(player)
      if (!made) {
        console.warn('[valley] FTB Teams did not report a party for ' + name +
                     '; quest progress will be keyed on their login name.')
        return
      }
      if (!pdGet('valley_team', null)) {
        pdPut('valley_team', made)
        console.info('[valley] the pack party is "' + made + '" (created by ' + name + ')')
      } else if (made !== pdGet('valley_team', null)) {
        console.warn('[valley] ' + name + ' is on party "' + made + '", not "' +
                     pdGet('valley_team', null) + '". They keep their own quest book.')
      }
    })
  })
}

// =============================================================================
// 5b. WHAT USED TO BE HERE, AND WHY IT IS NOT.
//
// Three hundred lines: RUIN_BEARINGS / RUIN_DIST / RUIN_SKIP, ruinSurface(), ruinSiteOk(),
// ruinPath(), placeRuin() and spawnSignpost(). Between them they searched eight bearings at
// three distances for somewhere flat enough to cut a pad, ran a datapack function that cut
// it, dragged a three-wide dirt-path corridor with lantern posts every six blocks from
// spawn to it, and stood a sign at the head of it — all in the first tick of the first
// login, all with `fill` and `setblock`, all on ground the seed had made and nobody had
// looked at.
//
// Every one of those things is in the shipped world:
//
//   the farm      day1_cottage, standing, cold, three walls and a chimney, its door and
//                 windows and bed left out for Q3, its hearthstone bare for Q2
//   the road      day1_road — the lantern road from spawn to the farm gate, graded into
//                 the hillside by the planner's skirt pass, not stamped on top of it
//   the signpost  day1_signpost, at the fork where the road leaves spawn
//   the cellar    day1_cellar, forty blocks of gravel and a sealed iron door under it
//
// So the first join hands over the letter, the compass, the book, the deed and the kettle,
// turns the player to face the farm, and says where it is. Nothing is written to the world.
// =============================================================================

// The four pages of Josie's Letter. Q1's one instruction is "read all four
// pages", and valley:letter was a plain KubeJS item with a rarity tint and no
// right-click behaviour — clicking it did nothing, there were no pages, and the
// quest was ticked the moment it landed in her bag. A vanilla written_book opens
// the real book screen on the first click: four pages, arrows, no mod involved
// and no NBT key we have to guess right.
const LETTER_PAGES = [
  "I wrote three of these and posted them all. Whichever of you is reading it: I'm dead, the valley is cold, and the farm is yours.\n\nSo is the kettle. So is the mess.",
  "A few of us stayed. Marnie keeps an inn with no guests. Bram keeps a mill with a snapped axle. Oda opens a shop nobody walks into and writes the takings down.\n\nThey are not stubborn. They are waiting. Don't tell them I said so.",
  "Forty lamp posts stand along the road and not one is lit. I lit them once. Then I put them out, on purpose.\n\nThere is a door in the cellar. Leave it shut until somebody can read my handwriting. It is not a riddle. It is a lock.",
  "The map, then. Follow the road from where you woke. It is signposted, and it ends at my gate.\n\nPut the waystone on the flat grey hearthstone in the middle of the kitchen floor and name it Home. Start from the part that held.\n\nPut the kettle on. \u2014 Josie"
]

// Built fresh per player: an ItemStack handed to two people is one stack.
function josieLetter() {
  try {
    // title / author / pages are exactly what WrittenBookItem.makeSureTagIsValid
    // requires (string, string, list). `generation` is deliberately absent: a JS
    // number comes through the KubeJS NBT converter as a DOUBLE, and while
    // getInt() survives that, an un-written key reads as 0 with no surprises.
    return Item.of('minecraft:written_book', {
      title: "Josie's Letter",
      author: 'Josie Kettle',
      pages: LETTER_PAGES.map(page => JSON.stringify({ text: page }))
    })
  } catch (err) {
    // Never let the letter cost somebody their first join. The keepsake item is
    // still registered and Q1's task is a checkmark she can tick by hand.
    console.error('[valley] could not build the written letter (' + err + '); ' +
                  'handing over valley:letter instead.')
    return Item.of(VALLEY.ITEM.letter)
  }
}

global.valley.letter = josieLetter

// -----------------------------------------------------------------------------
// Orientation. "When I spawned in, I had no clue what to do or where to go."
// Chat scrolls away and a letter in a bag is invisible, so the first minute is
// said on every channel there is: the body (face the path), the screen (a second
// title card, then the action bar until Q2 is done), the world (a signpost and
// a lit corridor) and the hand (a compass that points at the hearth).
// -----------------------------------------------------------------------------
function yawToward(from, to) {
  let dx = to[0] - from[0], dz = to[2] - from[2]
  return Math.round(Math.atan2(-dx, dz) * 180 / Math.PI)
}

// Turn the player to face the hearth. The hearth is a registry constant, so this is the
// same yaw for every player on every world and it cannot fail for want of a ruin.
function facePath(server, player, name) {
  let hearth = global.valley.hearth()
  if (!hearth) return
  let yaw = yawToward([player.x, player.y, player.z], hearth)
  server.runCommandSilent('tp ' + name + ' ' + player.x + ' ' + player.y + ' ' + player.z + ' ' + yaw + ' 8')
}

// The compass is a lodestone compass pointed at the hearthstone from the registry — the
// flat grey block in the middle of the cottage floor that Q2's waystone goes on.
function kettleFarmCompass() {
  let hearth = global.valley.hearth()
  let tag = hearth
    ? 'LodestonePos:{X:' + hearth[0] + ',Y:' + hearth[1] + ',Z:' + hearth[2] + '},LodestoneDimension:"minecraft:overworld",LodestoneTracked:0b,'
    : ''
  return 'minecraft:compass{' + tag +
    'display:{Name:\'{"text":"Kettle Farm Compass","italic":false,"color":"gold"}\',' +
    'Lore:[\'{"text":"It points at the hearth.","color":"gray","italic":true}\']}}'
}

// Which way the farm is from spawn, in words, worked out once from the registry rather
// than stored from whatever direction a search happened to pick.
function hearthBearing() {
  let hearth = global.valley.hearth()
  let spawn = global.valley.site('spawn')
  if (!hearth || !spawn) return 'south'
  let dx = hearth[0] - spawn[0], dz = hearth[2] - spawn[2]
  let ns = dz > 0 ? 'south' : 'north'
  let ew = dx > 0 ? 'east' : 'west'
  if (Math.abs(dx) * 2 < Math.abs(dz)) return ns
  if (Math.abs(dz) * 2 < Math.abs(dx)) return ew
  return ns + '-' + ew
}

function tellWhere(server, name, where) {
  valleyDelay(90, s => {
    s.runCommandSilent('title ' + name + ' times 10 70 20')
    s.runCommandSilent('title ' + name + ' subtitle ' +
      JSON.stringify({ text: 'to the gate with her name on it. Your letter is in your hand.', color: 'gray' }))
    s.runCommandSilent('title ' + name + ' title ' +
      JSON.stringify({ text: 'Follow the road ' + (where || 'south'), color: 'gold' }))
    s.runCommandSilent('execute at ' + name + ' run playsound minecraft:block.note_block.bell master ' + name + ' ~ ~ ~ 1 1.2')
  })
}

// The objective is said ONCE per step, not every three seconds (the repeating
// bar was "really, really annoying"). Three steps: read the letter, walk to the
// farm, put the waystone on the hearthstone. After the letter is read a thin
// column of light rises from the hearthstone until the waystone is on it, so
// "the flat grey stone" is the one you can see from the gate.
function objectiveState(player) {
  let v = global.valley
  let team = v.teamId(player)
  if (v.isDone('q02', team)) return 'done'
  if (!v.isDone('q01', team)) return 'letter'
  let hearth = v.hearth()
  if (!hearth) return 'book'
  let d = Math.sqrt(Math.pow(hearth[0] - player.x, 2) + Math.pow(hearth[2] - player.z, 2))
  return d <= 12 ? 'hearth' : 'walk'
}

function objectiveLine(state) {
  if (state === 'letter') return { text: 'Read Josie\'s letter. It is in your hand: right-click.', color: 'gold' }
  if (state === 'book') return { text: 'Open the Quest Book (right-click it, or press J).', color: 'gold' }
  if (state === 'walk') return { text: 'The Homestead Waystone is in your bag. Follow the road and the compass to the farm.', color: 'gold' }
  if (state === 'hearth') return { text: 'Put the Homestead Waystone on the flat grey hearthstone, where the light rises, and name it Home.', color: 'gold' }
  return null
}

function objectiveLoop() {
  let server = global.valleyServer
  if (!server) return
  let v = global.valley
  global.valleyObjectiveSeen = global.valleyObjectiveSeen || {}
  let anyLit = false
  try {
    server.players.forEach(pl => {
      let name = v.pname(pl)
      let state = objectiveState(pl)
      if (state !== 'done' && state !== 'letter') anyLit = true
      if (global.valleyObjectiveSeen[name] === state) return
      global.valleyObjectiveSeen[name] = state
      let line = objectiveLine(state)
      if (line) server.runCommandSilent('title ' + name + ' actionbar ' + JSON.stringify(line))
    })
    // the hearth light: only while someone has read the letter and not yet placed the waystone
    let hearth = v.hearth()
    if (anyLit && hearth) {
      server.runCommandSilent('particle minecraft:end_rod ' + hearth[0] + '.5 ' + (hearth[1] + 1.2) + ' ' + hearth[2] + '.5 0.15 0.6 0.15 0.005 4 force')
    }
  } catch (err) {
    console.warn('[valley] objective loop: ' + err)
  }
  valleyDelay(20, objectiveLoop)
}

function startObjectiveLoop() {
  if (global.valleyObjectiveLoop) return
  global.valleyObjectiveLoop = true
  valleyDelay(40, objectiveLoop)
}

global.valley.orient = function (server, player) {
  let name = global.valley.pname(player)
  facePath(server, player, name)
  tellWhere(server, name, hearthBearing())
  server.runCommandSilent('give ' + name + ' ' + kettleFarmCompass() + ' 1')
  startObjectiveLoop()
}


function valleyFirstJoin(server, player, name) {
  // The letter, the deed and the kettle. Q1's task is READING the letter, which
  // valley_checks.js ticks off the right-click that opens the book.
  // Hotbar order is the tutorial: the letter lands in the selected slot.
  player.give(josieLetter())

  // Title card. Exactly the words in §2.
  server.runCommandSilent('title ' + name + ' times 20 90 30')
  server.runCommandSilent('title ' + name + ' subtitle ' +
    JSON.stringify({ text: 'Spring, Year One.', color: 'gray', italic: true }))
  server.runCommandSilent('title ' + name + ' title ' +
    JSON.stringify({ text: 'LITTLE KETTLE VALLEY', color: 'gold', bold: true }))
  // `~ ~ ~` resolves against the COMMAND SOURCE, and runCommandSilent runs as
  // the server (0 0 0, overworld) — so the sound has to be run `execute at`
  // the player or nobody hears it.
  server.runCommandSilent('execute at ' + name + ' run playsound minecraft:block.note_block.chime master ' + name + ' ~ ~ ~ 1 0.8')

  // The farm, the road, the signpost and the lit gate are ALREADY THERE. Spawn is fixed by
  // the world (scratch/master_build.sh runs `setworldspawn` from the registry with a yaw
  // that already faces the road), so nothing here places a block or moves the spawn point:
  // the first join hands over the kit, turns her round and tells her where to walk.
  let hearth = global.valley.hearth()
  let where = hearthBearing()

  player.give(Item.of('ftbquests:book'))
  player.give(Item.of(VALLEY.ITEM.deed))
  player.give(Item.of(VALLEY.ITEM.kettle))
  if (hearth) server.runCommandSilent('give ' + name + ' ' + kettleFarmCompass() + ' 1')
  valleyDelay(5, s => { try { facePath(s, player, name) } catch (err) {} })
  // A5: NO second title card here. tellWhere() fires one 4.5 seconds after the
  // LITTLE KETTLE VALLEY card, and two title cards that close together read as a
  // cutscene she cannot skip. The same destination, with coordinates, is chat line
  // two below, and the actionbar repeats it on every state change. tellWhere() is
  // still live on global.valley.orient for a player who asks to be re-pointed.
  startObjectiveLoop()

  // A5: ONE title card and at most TWO chat lines. The premise lives in the letter
  // itself; chat only says what to do (writer-brief rule 3 keeps the destination
  // line verbatim). The third line -- "right-click the Quest Book" -- moved to the
  // self-dismissing login nudge in PlayerEvents.loggedIn, so it can repeat for a
  // player who never opens the book and vanish forever for one who does.
  let lines = [
    [{ text: 'A letter from ', color: 'white' }, { text: 'Josie Kettle', color: 'gold' },
     { text: ' is in your bag. Read all four pages.', color: 'white' }]
  ]
  if (hearth) {
    lines.push([
      { text: 'The lantern road at your feet runs ' + where + ' to the farm. Follow it to the gate \u2014 the hearthstone is at ', color: 'white' },
      { text: hearth[0] + ' ' + hearth[1] + ' ' + hearth[2], color: 'gold' },
      { text: '.', color: 'white' }
    ])
  }
  lines.forEach((l, i) => {
    valleyDelay(20 + i * 20, s => s.runCommandSilent('tellraw ' + name + ' ' + JSON.stringify(l)))
  })

  // The world border and the two counters start where §12.5 says they do.
  if (global.valley.once('world_opened')) {
    server.runCommandSilent('worldborder set 1500')
    server.runCommandSilent('bossbar set valley:folk value 0')
    global.valley.setLampsLit(0)
  }
  console.info('[valley] first join handled for ' + name + '; the farm is ' + where +
               ' at ' + (hearth ? hearth.join(' ') : '??'))
}

// =============================================================================
// 6. Handheld helpers the quests hand out.
//    §8 worked example 2: nobody waits on a chicken; the animals arrive in
//    crates and the feed makes a hen lay on use.
// =============================================================================
const CRATE_SPAWN = {
  'valley:hen_crate':   'minecraft:chicken',
  'valley:cow_crate':   'minecraft:cow',
  'valley:sheep_crate': 'minecraft:sheep'
}

// Q10 (three Hen Crates) and Q25 (Cow Crate + Sheep Crate).
Object.keys(CRATE_SPAWN).forEach(crateId => {
  ItemEvents.rightClicked(crateId, event => {
    let player = event.player
    if (player.level.isClientSide()) return
    let entityId = CRATE_SPAWN[crateId]
    let e = player.level.createEntity(entityId)
    if (!e) return
    e.setPosition(player.x, player.y, player.z)
    e.spawn()
    if (!player.isCreative()) event.item.count = event.item.count - 1
    global.valley.say(player, 'Marnie', 'Mind the gate. Those two would walk to the lake if you let them.')
  })
})

// Chicken feed: the nearest hen within 8 blocks lays immediately.
ItemEvents.rightClicked('valley:chicken_feed', event => {
  let player = event.player
  if (player.level.isClientSide()) return
  let box = new $AABB(player.x - 8, player.y - 4, player.z - 8, player.x + 8, player.y + 4, player.z + 8)
  let laid = 0
  player.level.getEntitiesWithin(box).forEach(e => {
    if (laid > 0) return
    if (String(e.type) !== 'minecraft:chicken') return
    let b = player.level.getBlock(Math.floor(e.x), Math.floor(e.y), Math.floor(e.z))
    b.popItem(Item.of('minecraft:egg'))
    laid++
  })
  if (laid > 0 && !player.isCreative()) event.item.count = event.item.count - 1
  if (laid === 0) global.valley.say(player, 'Marnie', 'She won\'t lay from over there. Stand in the pen with her.')
})

// Q26: the Dredge Net. Q22 pays the net and Q26's text promises "each pull
// brings up 16 Lake Sand" over eight pulls — but the item had no handler, so
// valley:lake_sand had NO source anywhere in the pack and Q26 (and the whole
// silica -> Thermal Machine Frame line behind it) was unwinnable. This is that
// handler: use it in Nella's boat, or anywhere with open water within reach.
const dredgeLast = {}

function dredgePull(player) {
  if (!player || player.level.isClientSide()) return

  // Open water anywhere in a small box around the player: covers sitting in the
  // boat (water below), standing on the pier lip, and wading from the shallows.
  let px = Math.floor(player.x)
  let py = Math.floor(player.y)
  let pz = Math.floor(player.z)
  let wet = false
  for (let dy = 1; dy >= -4 && !wet; dy--) {
    for (let dx = -2; dx <= 2 && !wet; dx++) {
      for (let dz = -2; dz <= 2 && !wet; dz++) {
        let b = player.level.getBlock(px + dx, py + dy, pz + dz)
        if (String(b.id) === 'minecraft:water') wet = true
      }
    }
  }
  if (!wet) {
    global.valley.say(player, 'Nella', 'Not on dry land. Get in the boat, out over the shallows.')
    return
  }

  // One pull a second: it also swallows the off-hand double-fire, so eight
  // pulls is eight pulls and not eight clicks.
  let now = Date.now()
  let name = global.valley.pname(player)
  if (now - (dredgeLast[name] || 0) < 1000) return
  dredgeLast[name] = now

  player.give(Item.of('valley:lake_sand', 16))

  let pulls = parseInt(global.valley.get('valley_dredge_pulls', '0'), 10) + 1
  global.valley.set('valley_dredge_pulls', pulls)
  if (pulls === 1) {
    global.valley.say(player, 'Nella', 'Sixteen. Hold the rope, don\'t help.')
  } else if (pulls === 8) {
    global.valley.say(player, 'Nella', "That's the eight - a hundred and twenty-eight. Bram's waiting.")
  }
}

// Right-clicking at open water fires RightClickItem...
ItemEvents.rightClicked('valley:dredge_net', event => { dredgePull(event.player) })

// ...but a player standing in the shallows is usually looking AT the lake bed,
// and a block under the cursor sends the interaction to RightClickBlock instead,
// where the item event never fires. Both paths pull the same net. Guarded so an
// API surprise here can never take the rest of the spine down with it.
try {
  BlockEvents.rightClicked(event => {
    if (String(event.item.id) !== 'valley:dredge_net') return
    dredgePull(event.player)
  })
} catch (err) {
  console.warn('[valley] dredge net: block-click path unavailable (' + err + ')')
}

console.info('[valley] valley_core.js ok')
