motd=Cozy Tech Pack
white-list=true
enforce-whitelist=true
difficulty=normal
view-distance=8
simulation-distance=6
spawn-protection=0
max-players=8
online-mode=true
enable-command-block=true
allow-flight=true
level-seed=
sync-chunk-writes=false
