name = "Kettle Tech"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79984ea5c4db486cbdd2ea62148fdf0aa7f5413e9f2157575b85711369df58bf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
