name = "Kettle Tech"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f41e06cb0a58a9ea565ba46ec31608a953aa003f87c028813bede28c70a0aad9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
