name = "Kettle Tech"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20c471d9815a6d8a5a9bf2acc97b1e6b67c779a68abe7b73af45720bad7df584"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
