name = "Little Kettle Valley"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "156fd9a97d7161e24448c54cf85e9591b0a5e0e17dbbd32c077b174693d32165"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
