name = "Little Kettle Valley"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65431705c1629a2fffde95901536325c0ddd26de9b476be673c6d2aec68b0faf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
