name = "Little Kettle Valley"
author = "Josh Malloy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d2f695e328af7638ca7c5b39fccd369373d477da5a44a07325c2003bbba737"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
